### PR TITLE
ID: unicode.ipynb load_data tutorials id translation

### PR DESCRIPTION
**Pull request by csahat**

### CODE REVIEW

**Comment by csahat** [comment]
> Preview and run these notebook edits with Google Colab:
> 
> * [site/id/tutorials/load_data/unicode.ipynb](https://colab.research.google.com/github/csahat/docs/blob/tutorials-load_data-unicode-id/site/id/tutorials/load_data/unicode.ipynb)
> 
> [Notebook diffs](https://app.reviewnb.com/tensorflow/docs/pull/1297/files/) available on ReviewNB.com.

Running well on Colab, no issues found. 
@febriaroo, @rendrat, please review

**Comment by lamberta** [comment]
Thank you, @csahat (and apologies for the repetitive comments in your PRs :)

Community translations are now located in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo (see [this message](https://groups.google.com/a/tensorflow.org/g/docs/c/GJPq7S_fw4c/m/lA1qfBX2EQAJ) for context).

I'll move over/duplicate existing pull requests as I find time. In the meantime, please feel free to create a new pull request in that repo 😀 Then you can close this PR and add a link to the new one.

**Comment by csahat** [comment]
> Thank you, @csahat (and apologies for the repetitive comments in your PRs :)
> 
> Community translations are now located in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo (see [this message](https://groups.google.com/a/tensorflow.org/g/docs/c/GJPq7S_fw4c/m/lA1qfBX2EQAJ) for context).
> 
> I'll move over/duplicate existing pull requests as I find time. In the meantime, please feel free to create a new pull request in that repo 😀 Then you can close this PR and add a link to the new one.

Hi @lamberta, it seems my PRs have not been reviewed since December 13th. For now, I will just hold on to create a new translation.

**Comment by lamberta** [comment]
Yes, without a community of reviewers to support it, it can sometimes be counterproductive to create new notebooks :)

But no more translations will be merged into this repo. To get this in, it will need to be moved over to to the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo.

**Comment by csahat** [comment]
@lamberta I have created a new PR here https://github.com/tensorflow/docs-l10n/pull/25. Thanks

**Comment by csahat** [comment]
> Yes, without a community of reviewers to support it, it can sometimes be counterproductive to create new notebooks :)
> 

Hi @lamberta, I want to nominate my self to become community reviewers for ID translation. I have put my Github id on the REVIEWERS file. Let me know what to do next.

**Pull request closed without merging**
