### PR TITLE
[Intel MKL] Adding instructions for building TF on CPU with MKL-DNN support

### PR DESCRIPTION
**Pull request by mahmoud-abuzaina**

### CODE REVIEW

**Comment by gunan** [comment]
This is not a configuration we are officially testing, verifying that it works.
@lamberta I will leave it up to you to decide where we should document this.

**Comment by lamberta** [comment]
Thanks, @gunan 

@mahmoud-abuzaina since this is not a configuration we can test and verify, a better place to put this is in the community docs section of the examples repo: https://github.com/tensorflow/examples/tree/master/community/en/docs
We could potentially link off to that from the install/ section.

Closing this PR, but feel free to submit a PR in the other repo.
Thanks, all.

**Comment by mahmoud-abuzaina** [comment]
@lamberta does the examples repo you mentioned get published somewhere? Also do you recommend to create a directory for MKL under docs? Thanks!

**Comment by lamberta** [comment]
The community docs repo is not published on tensorflow.org and can be used for unofficial solutions provided by the community. If you are submitting multiple MKL docs, then a directory might be worthwhile. Otherwise, perhaps a `install-mkl.md` file?

**Pull request closed without merging**
