### PR TITLE
Update images.ipynb

### PR DESCRIPTION
**Pull request by kaimo455**
Change at line 468, follow the tf.image.resize, the new size format should be [IMG_HEIGHT, IMG_WIDTH]

### CODE REVIEW

**Comment by lamberta** [comment]
Thanks. Before we can merge, can you please sign the CLA: https://cla.developers.google.com/

**Comment by kaimo455** [comment]
> Thanks. Before we can merge, can you please sign the CLA: https://cla.developers.google.com/

Signed.

**Comment by kaimo455** [comment]
@googlebot I signed it!

**Comment by nemesszili** [comment]
Also discovered this a while ago, good catch!

**Comment by MarkDaoust** [comment]
Darn square images...

**Pull request merged**
