### PR TITLE
fixed tensorflow issue https://github.com/tensorflow/tensorflow/issues/75194

### PR DESCRIPTION
**Pull request by sanskarmodi8**
Edited the compile_and_fit method in the overfit_and_underfit.ipynb notebook to correctly pass the train and val data to avoid shape mismatch error.

### CODE REVIEW

**Comment by sanskarmodi8** [comment]
Are there any updates on this?

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Hi, it looks like this PR includes your changes from  https://github.com/tensorflow/docs/pull/2324.

Can you `git rebase -i master` to remove that commit and then `git push -f` to remove it from this PR?

At the same time can you remove outputs from the notebook?

**Comment by sanskarmodi8** [comment]
> Hi, it looks like this PR includes your changes from #2324.
> 
> Can you `git rebase -i master` to remove that commit and then `git push -f` to remove it from this PR?
> 
> At the same time can you remove outputs from the notebook?

Sure. Working on it

**Comment by sanskarmodi8** [comment]
Hey @MarkDaoust ,
Any updates on this?
I have removed changes from #2324

**Review by MarkDaoust — APPROVED** [review]

**Pull request merged**
