### PR TITLE
Nit: Lint the Classify text with BERT tutorial

### PR DESCRIPTION
**Pull request by 8bitmp3**
@lamberta @MarkDaoust Very small changes (commas and spelling, such as "optimizer", "URL", "yield"). It's a nice tutorial about using a pre-trained Transformer for NLP, it's very hot these days.

### CODE REVIEW

**Review by lamberta — APPROVED** [review]
Thanks!

**Comment by lamberta** [comment]
Hmm, still problems. Lemme see if i can fix

**Review by lamberta — APPROVED** [review]
That should do it

**Comment by 8bitmp3** [comment]
@lamberta Thanks 👍 I was wondering why `git push` didn't work after my `git commit -m "Apply nbfmt"`

**Pull request merged**
