### PR TITLE
RU: Pix2Pix

### PR DESCRIPTION
**Pull request by 0101011**

### CODE REVIEW

**Comment by 0101011** [comment]
One notebook per day keeps the repo fresh

**Comment by 0101011** [comment]
Yep, the gist of the notebook will be somewhat the same and the technique can be implemented in various ways.

I’ll get to localize more notebooks w/o an underscore from images/ folder since this is my favorite field 🍰

**Comment by yashk2810** [comment]
This notebook is getting changed and being moved to r2/. I would wait until that's done.

**Comment by yashk2810** [comment]
New version: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/images/pix2pix.ipynb

**Comment by lamberta** [comment]
Hey Andrew, I'm doing a little Spring cleaning on old pull requests.
Feel free to re-open, or create a new one, if you continue with the pix2pix notebook. Thanks

**Comment by 0101011** [comment]
@lamberta Hey Billy, this notebook is fully translated as far as I can remember — do you have a fresh one for reopening?

The reason I’m asking is last time checked I was unable to locate one in this repo.

**Comment by lamberta** [comment]
Ah, ok. Looks like things have moved around and this is now here: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/generative/pix2pix.ipynb

Can you rename the file name and check to see if it still matches?
Thanks!

**Comment by 0101011** [comment]
Sure, will be here in 2 hrs, thanks for the poke!

**Pull request closed without merging**
