### PR TITLE
Update nvidia driver version in gpu install instructions

### PR DESCRIPTION
**Pull request by nluehr**
Update driver version for Ubuntu 18.04 apt install from 430 to 450 to resolve packaging issues reported in [tensorflow issue 40278](https://github.com/tensorflow/tensorflow/issues/40278).

Attention @sanjoy

### CODE REVIEW

**Comment by yashk2810** [comment]
450 won't work with stable tensorflow right?

**Comment by gunan** [comment]
It should work. Why do you think it wont work?

**Comment by yashk2810** [comment]
Oh right it will. Cuda 11 won't work with that.

Anyways 450 is not available on rapture yet. I just tried that comma d out yesterday and it didn't work.

**Comment by yashk2810** [comment]
@nluehr Can you paste the output of nvidia-smi from your try on the instructions and also the output of the command that you are updating here?

**Comment by nluehr** [comment]
Here is my nvidia-smi output. The CUDA_VERSION listed in the first row of output is the maximum toolkit version supported by the driver. The 11.0 CUDA toolkit is not installed with the driver.

```
Thu Jul  9 12:19:17 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 6000     Off  | 00000000:01:00.0 Off |                  Off |
| 33%   37C    P8    13W / 270W |    367MiB / 24220MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1683      G   /usr/lib/xorg/Xorg                363MiB |
+-----------------------------------------------------------------------------+
```

**Pull request merged**
