### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by mpicek**

### CODE REVIEW

**Comment by lamberta** [comment]
Thanks for the fix, @mpicek
For us to merge, can you please sign the CLA? https://cla.developers.google.com/

**Comment by mpicek** [comment]
@googlebot I signed it!

**Review by lamberta — APPROVED** [review]
Thanks!

**Comment by mpicek** [comment]
@lamberta, now I have signed it. Sorry, I'm now to this :)

**Comment by Nikhil0504** [comment]
Hey @lamberta should just do PR for changing the grammar and typo without rising any issue?

**Pull request merged**
