### PR TITLE
fixed issue https://github.com/tensorflow/tensorflow/issues/75196

### PR DESCRIPTION
**Pull request by sanskarmodi8**
fixed several issues in save_and_load.ipynb notebook in keras tutorials as mentioned in Tensorflow issue #75196

### CODE REVIEW

**Review by MarkDaoust — DISMISSED** [review]
LGTM.

**Comment by MarkDaoust** [comment]
Fixed. Thanks!

**Comment by sanskarmodi8** [comment]
> Fixed. Thanks!
> 

Thanks for pointing it out and pushing changes. I will format the notebook and push it soon enough.

**Comment by sanskarmodi8** [comment]
I have formatted the notebook using nbfmt after considering your mkdir change so that it pass the lint check it was failing earlier

**Comment by MarkDaoust** [comment]
LGTM. Thanks, this is being merged. It will complete soon.

**Comment by sanskarmodi8** [comment]
> LGTM. Thanks, this is being merged. It will complete soon.

Thank you. Actually, it was failing a linting test as I didn't used proper linting so I applied proper linting and then pushed the commit

**Comment by sanskarmodi8** [comment]
Hey @MarkDaoust ,
Any updates on this?

**Pull request merged**
