### PR TITLE
Basic tutorials update for v2.0 (learn-and-use-ml)

### PR DESCRIPTION
**Pull request by KentoNishi**
I am in the process of learning TF, and I noticed that the tutorials are not compatible with v2 alpha. I fixed all the conflicts, and updated the notebooks accordingly.
I am working through all the remaining tutorials and editing the notebooks as I go, so I will add more in the future.
This is my first time contributing to TF. If there is anything important, please let me know!

### CODE REVIEW

**Comment by KentoNishi** [comment]
I signed it!

**Comment by KentoNishi** [comment]
I made a mistake in the request. Closing.

**Comment by lamberta** [comment]
Hi Kento, thank you for taking a look! No worries, let us know how it goes as you work through the rest.

The TF 2.0 Alpha tutorials are linked on this page: https://www.tensorflow.org/alpha
and live here in GitHub: https://github.com/tensorflow/docs/tree/master/site/en/r2

We use Colab notebooks for our tutorials (.ipynb) which are converted to Markdown when imported into the site. So we don't want to convert them to Python files here.

For fixes, you can open a [notebook in Colab](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/r2/tutorials/keras/basic_classification.ipynb), make changes directly in Colab, then download an .ipynb file and create a pull request here.

Good luck!

**Comment by KentoNishi** [comment]
Ahh, thanks! I was a bit confused there.

**Pull request closed without merging**
