### PR TITLE
it - translate community-contribute-index

### PR DESCRIPTION
**Pull request by maryggiannella**
You will find here the translation for the file `index.md` inside the directory community/contribute

### CODE REVIEW

**Comment by lamberta** [comment]
@shivaylamba Are you reviewing the Italian translation?

**Comment by shivaylamba** [comment]
@lamberta I used Google Translate to see in case there is any mis match as compared to the English docs. And it seems to be fine.

**Comment by lamberta** [comment]
@shivaylamba Thanks, but please let the Italian translation community review first before Google Translate :) Google Translate is great for checking for serious problems, but misses a lot of things that native speakers catch.

**Comment by shivaylamba** [comment]
@lamberta Ok Thankyou Billy! I will keep that in mind from now on.

**Comment by lamberta** [comment]
@shivaylamba Thanks!
Now that I think about it, there are are number of [Indonesian pull requests](https://github.com/tensorflow/docs/pulls?q=is%3Apr+is%3Aopen+label%3Aid) that are waiting around for review. It would be very helpful to check these with Google Translate and approve. Just note in your review that it looks fine in Google Translate. It's a balance of quality vs timing. Ideally, the community reviews, but after a while, it's better to just get it in and iterate (as long as it's checked for spam, etc.)

**Comment by shivaylamba** [comment]
@lamberta Sure I would love to review those PRs. I will make sure that none of them are spam or have irrelevant content.

**Comment by lamberta** [comment]
Thank you.

Community translations are now located in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo (see [this message](https://groups.google.com/a/tensorflow.org/g/docs/c/GJPq7S_fw4c/m/lA1qfBX2EQAJ) for context).

I'll move over/duplicate existing pull requests as I find time. In the meantime, please feel free to create a new pull request in that repo 😀 Then you can close this PR and add a link to the new one.

**Comment by lamberta** [comment]
Migrated in https://github.com/tensorflow/docs-l10n/pull/95

**Pull request closed without merging**
