### PR TITLE
Word Embeddings

### PR DESCRIPTION
**Pull request by securetorobert**
This is the first version of our Keras embeddings tutorial.

https://colab.sandbox.google.com/github/securetorobert/docs/blob/master/site/en/tutorials/keras/intro_word_embeddings.ipynb

### CODE REVIEW

**Comment by random-forests** [comment]
Thanks for the feedback! Good comments. Thinking about this more, how does the following sound?

* We can include a section on using pre-trained embeddings.

* We can use a more sophisticated CNN-based model, perhaps from the right side of this flow chart: https://developers.google.com/machine-learning/guides/text-classification/step-2-5 (others are working on an RNN tutorial at the moment, so  I don't think we need to include that part here).

From there, we can include a few diagrams helping to communicate the basic idea of embeddings. WDYT?

**Comment by securetorobert** [comment]
I will review the comments above and implement in a little bit. Thanks guys.

**Comment by securetorobert** [comment]
@random-forests do you need to provide consent for the CLA above?

**Comment by securetorobert** [comment]
@random-forests kindly take a look at the recent updates. Thanks

**Comment by securetorobert** [comment]
@MarkDaoust kindly review recent changes, thanks.

**Comment by random-forests** [comment]
Hi Robert, thanks again for working on this! I will circle back in a week or so (been OOO for a bit, please stay tuned).

**Comment by random-forests** [comment]
I'm only a few months late here (wowzers, my bad!) I'm going to close this PR out, and work on a new version for a bit. Will definitely credit you when we get it out! Thanks again for your help, and sorry again for the delay.

**Pull request closed without merging**
