### PR TITLE
ID: Add keras tutorials text_classification.ipynb indonesian translation

### PR DESCRIPTION
**Pull request by csahat**

### CODE REVIEW

**Comment by csahat** [comment]
> Preview and run these notebook edits with Google Colab:
> 
> * [site/id/tutorials/keras/text_classification.ipynb](https://colab.research.google.com/github/csahat/docs/blob/keras-text_class-trans-id/site/id/tutorials/keras/text_classification.ipynb)
> 
> [Notebook diffs](https://app.reviewnb.com/tensorflow/docs/pull/1288/files/) available on ReviewNB.com.

Ran with some issues on Colab, but no issues when running locally. 

@febriaroo, @rendrat, how do you want to deal with it?

**Comment by lamberta** [comment]
Thanks for testing on Colab!
Looks like the English source notebook is also affected: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification.ipynb

@MarkDaoust is looking at a fix, seems TFDS related. cc: @yashk2810 @conchylicultor

**Comment by lamberta** [comment]
Thank you.

Community translations are now located in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo (see [this message](https://groups.google.com/a/tensorflow.org/g/docs/c/GJPq7S_fw4c/m/lA1qfBX2EQAJ) for context).

I'll move over/duplicate existing pull requests as I find time. In the meantime, please feel free to create a new pull request in that repo 😀 Then you can close this PR and add a link to the new one.

**Comment by csahat** [comment]
@lamberta I have created new PR in this link https://github.com/tensorflow/docs-l10n/pull/18. Thank you.

**Pull request closed without merging**
