### PR TITLE
JA: translation r2/lite/convert

### PR DESCRIPTION
**Pull request by ohtaman**
Translate https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/g3doc/r2 and copy to lite/

### CODE REVIEW

**Comment by masa-ita** [comment]
index.md contains a few 'back spaces' (0x08)

**Comment by masa-ita** [comment]
In cmdline.md, I prefer ’説明’ to 'インストラクション'.

**Comment by masa-ita** [comment]
Comments on concrete_function.md.

Weak suggestion:

I prefer '方法論' or  just '方法' as a translation for 'Methodology'.

Suggestions:

'###具象関数をエクスポートする' should be '### 具象関数をエクスポートする'.

'# tf.Moduleオブジェクトのいち部として関数を保存' should be '# tf.Moduleオブジェクトの一部として関数を保存'.

'保存処理中にモデル関数が生成されるので' should be '保存処理中に具象関数が生成されるので'.

**Comment by masa-ita** [comment]
In python_api.md:

'model_content の代わりに model_path を使用しています。' should be 'model_content の代わりに model_path を使用します。'.

**Comment by lamberta** [comment]
There have been changes in the source docs so this pull request looks a little stale: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/g3doc/convert

Can you update (or close) this PR depending on what you'd like to do? Thanks

**Comment by ohtaman** [comment]
Thanks. I'll update this translation.

**Comment by ohtaman** [comment]
@masa-ita @lamberta 
I updated translations following the reviewer's opinion and the change of the original documents.

The original document is not at  
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/g3doc/convert
but
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/g3doc/r2/convert

**Comment by masa-ita** [comment]
@ohtaman 
I've reviewed then changes you made.
LGTM

**Pull request merged**
