### PR TITLE
Lint TensorFlow: Better performance with `tf.function`

### PR DESCRIPTION
**Pull request by 8bitmp3**
Splitting PR #1736 into smaller digestible bits. Appreciate it @lamberta @MarkDaoust

### CODE REVIEW

**Comment by 8bitmp3** [comment]
I think the use of the word "native"—as in "native TensorFlow"—may be causing the CI test (`nblint`) to ❎:

```
APIs like `tf.gather`, `tf.stack`, and `tf.TensorArray` can help you implement common
looping patterns in native TensorFlow.
```

**Comment by 8bitmp3** [comment]
Gently pinging @MarkDaoust @lamberta

**Comment by lamberta** [comment]
Merge conflict, please resolve

**Comment by 8bitmp3** [comment]
Yup, it's "native TensorFlow", which I can't resolve at the moment: `Fail | google::inclusive_language | Use inclusive language: https://developers.google.com/style/inclusive-documentation`:

```
        "APIs like `tf.gather`, `tf.stack`, and `tf.TensorArray` can help you implement common looping patterns in native TensorFlow."
```

**Pull request closed without merging**
