### PR TITLE
Fixed missing code in word2vec

### PR DESCRIPTION
**Pull request by apeltop**
Existing code was not load the TensorBoard notebook extension before using embedded TensorBoard viewer

### CODE REVIEW

**Comment by apeltop** [comment]
@googlebot I signed it!

**Comment by 8bitmp3** [comment]
@apeltop Good catch!

It might be a better idea to load TensorBoard at the beginning in the notebook cell that import all the packages. For example:

```diff
...
import tensorflow as tf
import tqdm
from tensorflow.keras import Model, Sequential
from tensorflow.keras.layers import Activation, Dense, Dot, Embedding, Flatten, GlobalAveragePooling1D, Reshape
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization
+ 
+ # Load the TensorBoard notebook extension
+ %load_ext tensorboard
```

This way, you load TB and "forget about it" long before you create the TB callback.

(https://www.tensorflow.org/tensorboard/tensorboard_in_notebooks, https://www.tensorflow.org/tensorboard/get_started)

**Comment by apeltop** [comment]
@8bitmp3 Thank you for your guidance. I modified it according to you advice.

**Comment by 8bitmp3** [comment]
@lamberta @MarkDaoust PTAL, thanks 👍

**Comment by 8bitmp3** [comment]
Hey @apeltop Thanks again for this PR. It looks like the feature you wanted to introduce was bundled into this PR https://github.com/tensorflow/docs/pull/1877/files. I was already in the process of resolving a merge conflict to help you have the PR approved when I noticed that. In any case, thank you very much for spotting the missing TensorBoard loading step. We appreciate your input and can't wait to see your future contributions 👍

**Pull request closed without merging**
