### PR TITLE
Upgrades of the Russian translation of basic classification doc

### PR DESCRIPTION
**Pull request by ilyaerin**
**Issue with description**: https://github.com/tensorflow/tensorflow/issues/26044

### CODE REVIEW

**Comment by lamberta** [comment]
Nice, thanks! (Please sign the CLA :)

@0101011 Can you please take a look?

I think—at some point—we should hammer out a style guide. But, in the meantime, feel free to propose changes to the [Russian README](https://github.com/tensorflow/docs/blob/master/site/ru/README.md) and perhaps we can come to some agreements there. (If you have ideas as you work through other tutorials on the site.)

**Comment by ilyaerin** [comment]
I signed it!

**Comment by 0101011** [comment]
Hi Ilya, thanks for the fixes!

@lamberta These are the additions and corrections to make things more easily understandable, and some things we’ve missed while proofreading

Would vote to merge 👍

**Comment by ilyaerin** [comment]
@lamberta @0101011 thanks a lot for the so fast reaction and checking!

**Comment by 0101011** [comment]
@0101011 yep, I’m reading this night 😃 feel free to share more fixes as you read other docs too, we literallly brute-forced some vocabulary a month ago — might feel inconsistent a bit as you read through

**Comment by ilyaerin** [comment]
@0101011 @lamberta ok. I'm going to read the documentation next in the next week. If I find any other places to upgrade, I will definitely do it, especially after this super fast checking :)

**Comment by lamberta** [comment]
FYI, I republished the latest translations yesterday but we've entered a site freeze until Dev Summit. Please feel free to make fixes, but it may be another week or so before tensorflow.org is updated.

**Comment by ilyaerin** [comment]
@lamberta thanks for the explanation. it's ok.

**Comment by dynamicwebpaige** [comment]
Thanks for noticing this, and for making the modifications to the docs! We appreciate it. :smile:

**Pull request merged**
