### PR TITLE
Update groups.md

### PR DESCRIPTION
**Pull request by monk1337**
Add Tensorflow India group. 
Created on 29 April 2017
Current tf Members :  4,261
Group link : https://www.facebook.com/groups/tensorflowindia/

The current Mumbai group link  (TensorFlow UserGroup Mumbai) is not active, please remove it

### CODE REVIEW

**Comment by monk1337** [comment]
@googlebot I signed it!

**Comment by monk1337** [comment]
@soonson Sure, But this is very old group and we have many active members here. We promote research, discussion on the latest TensorFlow models, we add the latest state-of-art papers.

**Comment by monk1337** [comment]
Sent a mail.

**Comment by soonson** [comment]
Excellent. Let's discuss there further.

**Comment by monk1337** [comment]
@lamberta Can you please review it?

**Comment by soonson** [comment]
Hi: we've been discussing this internally and relevant people will get back to you soon. Thank you.

**Comment by lamberta** [comment]
cc: @gandhinikita01

**Comment by lamberta** [comment]
Closing this issue since the review is happening elsewhere and I think an email thread is going.

And we're using a new process to submit groups with [this form](https://docs.google.com/forms/d/e/1FAIpQLSc_RQIUYtVgLLihzATaO_WUXkEyBDE_OoRoOXYDPmBEvHuEBA/viewform) that's linked from https://www.tensorflow.org/community/groups

**Pull request closed without merging**
