### PR TITLE
Updated TensorFlow India Community URL

### PR DESCRIPTION
**Pull request by ialimustufa**
Updated TensorFlow India Community Link (From Facebook to Telegram)

### CODE REVIEW

**Comment by ialimustufa** [comment]
@googlebot I signed it!

**Comment by lamberta** [comment]
The [Facebook Group](https://www.facebook.com/tensorflowindia) still looks active so I'm not comfortable changing this. Do you have a community contact for this group?

**Comment by ialimustufa** [comment]
Hello, 

You can see me in team here: https://m.facebook.com/tensorflowindia/about/

Actually problem with Facebook is that Developers don't join it and hence I started the Telegram Group where they are more comfortable. We already have 600 members in our Telegram Group.

**Comment by lamberta** [comment]
Thanks. I've started a thread with some community folks to figure out a better process. Re-opening this PR but waiting on a response.

**Comment by ialimustufa** [comment]
Thankyou; waiting for a positive response!

**Comment by lamberta** [comment]
Thanks. Someone from the India community team will reach out

**Pull request closed without merging**
