### PR TITLE
Add neural style transfer tutorial

### PR DESCRIPTION
**Pull request by raskutti**
Based on discussion with Josh, clean up this blog (https://medium.com/tensorflow/neural-style-transfer-creating-art-with-deep-learning-using-tf-keras-and-eager-execution-7d541ac31398) to create a neural style transfer colab.

Also add a directory for example images that are referenced in the notebook.

### CODE REVIEW

**Comment by raskutti** [comment]
@random-forests @karmel

**Comment by random-forests** [comment]
Thank you for writing this! I'll make some updates in a week or two, stay tuned.

**Comment by MarkDaoust** [comment]
I had been leaning towards just merging in [Raymond's version](https://github.com/tensorflow/models/tree/master/research/nst_blogpost). I pulled in a copy with history, [here](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/eager/_style_transfer.ipynb)

That one's still hidden. Whatever you decide to do here just be sure we don't end up publishing two of these.

**Comment by lamberta** [comment]
Hi Kiran,

Apologies for the delay, our priorities have shifted with the lead up to TF 2.0 and the upcoming [TF Dev Summit](https://www.tensorflow.org/dev-summit).

For new notebooks, we're now adding them to the [tensorflow/examples/community](https://github.com/tensorflow/examples/tree/master/community/en) repo. Would you mind moving this pull request to that repo? This will allow us to merge changes quicker.

Thanks!

**Comment by raskutti** [comment]
No problem! I created https://github.com/tensorflow/examples/pull/6 in the community repo, and will revert this one shortly.

**Pull request closed without merging**
