### PR TITLE
Adding tutorial for Grad-CAM Heatmap Visualization

### PR DESCRIPTION
**Pull request by Qwerty71**
Hi! This is a pull request to add a tutorial for Grad-CAM Heatmap VIsualization. The notebook thoroughly explains how the technique works and implements it step-by-step to make it easier for readers to understand. Please let me know if you have any suggestions. Thanks!

### CODE REVIEW

**Comment by Qwerty71** [comment]
Not sure whether I need to confirm or not, but yes, I ran the notebook and it worked.

**Comment by lamberta** [comment]
Thanks, @Qwerty71 for the submission.

Unable to view the diff on this notebook---try downloading the notebook from Colab and save *without* outputs.

Adding the community review label and hopefully someone can take a look, please look through the [TensorFlow docs contributor guide](https://www.tensorflow.org/community/contribute/docs) and the [style guide](https://www.tensorflow.org/community/contribute/docs_style).

You can try the docs@tensorflow.org to find a technical and editorial reviewer, but without community support, we're unlikely to have time to review this in the short term. Thanks

**Comment by Qwerty71** [comment]
Thanks for the response! I'll save it without the outputs and try to fix the diff issue. I understand that the team is busy, so take your time.

**Comment by MarkDaoust** [comment]
Hi @Qwerty71, 

Thanks for the submission. It looks like we've got a similar tutorial submission in #1413, 
Please see the comments on there.

Maybe you and @Mbah-Javis can work together on finalizing a single tutorial? We don't have room for 2-heatmap vis tutorials, and I think you each cover points missed by the other? WDYT?

**Comment by lamberta** [comment]
PR stalled but thanks.
For community contributions, best to engage with the TensorFlow SIGS: https://github.com/tensorflow/community/tree/master/sigs
Or the ML GDEs: https://github.com/ml-gde

**Pull request closed without merging**
