### PR TITLE
Extended with unicode support.

### PR DESCRIPTION
**Pull request by muarvyn**
Added support for input files with UTF-8 encoding, Python 2 and Python 3 compatible. Tested on Python 2.7.15rc1 and Python 3.6.5.
Removed redundant lines of code.

### CODE REVIEW

**Comment by MarkDaoust** [comment]
@googlebot 
He signed it!

**Comment by muarvyn** [comment]
Thanks Mark for handling the request.
Seems I know how the problem with CLA arose: developers.google.com automatically caught my google email and attached to CLA, not my github email.

> The email used to register you as an authorized contributor must also be attached to your GitHub account.
- Fixed.

**Comment by muarvyn** [comment]
Function `repr()` is used pretty often in the code, but with unicode text it produces a peculiar output. For an instance, the code
```
sequences = char_dataset.batch(seq_length+1, drop_remainder=True)

for item in sequences.take(5):
  print(repr(''.join(idx2char[item.numpy()])))
```
produces the output like
u'\ufeff\u0414\u0436\u043e\u0430\u043d\u043d \u041a. \u0420\u043e\u043b\u0438\u043d\u0433\n\u0413\u0410\u0420\u0420\u0418 \u041f\u041e\u0422\u0422\u0415\u0420\n\u0438\n\u0424\u0418\u041b\u041e\u0421\u041e\u0424\u0421\u041a\u0418\u0419 \u041a\u0410\u041c\u0415\u041d\u042c\n\u0413\u043b\u0430\u0432\u0430 1\n\u041c\u0410\u041b\u042c\u0427\u0418\u041a, \u041a\u041e\u0422\u041e\u0420\u042b\u0419 \u0412\u042b\u0416\u0418\u041b\n\u041c\u0438\u0441\u0442\u0435\u0440 \u0438 \u043c\u0438\u0441\u0441\u0438\u0441 \u0414\u0443'...

And without use of `repr()` it produces a normal readable text.
Is it as expected to be?

Nevertheless, the text, produced by code 
`print(generate_text(model, start_string=u"Гарри"))`
is OK.

**Comment by lamberta** [comment]
Staged: https://colab.research.google.com/github/muarvyn/docs/blob/patch-1/site/en/tutorials/sequences/text_generation.ipynb

What's the status on this PR?
It looks like it needs to be rebased, anything else?

**Pull request merged**
