### PR TITLE
Update automatic_differentiation.ipynb

### PR DESCRIPTION
**Pull request by harmindergit**
grammatical correction

### CODE REVIEW

**Comment by harmindergit** [comment]
I signed it!

**Comment by lamberta** [comment]
Thank you. Can you also update the TF2 version? https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/eager/automatic_differentiation.ipynb

**Comment by lamberta** [comment]
Thanks! Can you try signing the CLA again at https://cla.developers.google.com/  ---the bot is having some issues finding you 🤖

**Comment by harmindergit** [comment]
I signed it!

**Comment by lamberta** [comment]
@harmindergit Were you able to fill out the form here: https://cla.developers.google.com/ ?
System isn't seeing you, yet

**Comment by harmindergit** [comment]
I signed it!

**Pull request merged**
