### PR TITLE
Lint TensorFlow: Distributed training with TF

### PR DESCRIPTION
**Pull request by 8bitmp3**
Splitting PR #1736 into smaller digestible bits. 

Note that the original notebook couldn't pass the `nblint` CI test (use of first person: "we", "our"), so PTAL:

```diff
- By integrating into `tf.keras` backend, we've made it seamless for you to distribute your training
+ By integrating into `tf.keras` backend, TensorFlow made it seamless for you to distribute your training
```

Thanks @lamberta @MarkDaoust 👍

### CODE REVIEW

**Comment by 8bitmp3** [comment]
Hi @lamberta HNY! 🎉 PTAL at a batch of small PRs from Dec when you have time 🙏 Thanks!

**Comment by 8bitmp3** [comment]
hi @lamberta @MarkDaoust can you PTAL thank you 👍

**Comment by lamberta** [comment]
Merge conflict, please resolve

**Comment by 8bitmp3** [comment]
Hi @lamberta merge conflict resolved and tests have passed, PTAL, thanks 👍

**Comment by 8bitmp3** [comment]
@lamberta @MarkDaoust PTAL, the last merge conflict should be resolved 👍 All test have passed

**Review by lamberta — APPROVED** [review]

**Comment by 8bitmp3** [comment]
Nice @lamberta Thanks. Fingers crossed - no merge conflicts here so far.

**Comment by lamberta** [comment]
May need to rebase and (force) push to your branch to re-trigger the GitHub CI

**Comment by 8bitmp3** [comment]
Updated the fork with the upstream `tensorflow:master` repo. Waiting for the commit (`Merge branch 'tensorflow:master' into lint-distributed-training`) to propagate into the PR.

**Comment by lamberta** [comment]
> Updated the fork with the upstream tensorflow:master repo. Waiting for the commit (Merge branch 'tensorflow:master' into lint-distributed-training) to propagate into the PR.

Can you clarify "propagate into the PR"? You need to manually rebase and push to your fix branch (your personal repo where the PR originated) and it will automatically show up here in the pull request.

**Comment by 8bitmp3** [comment]
The commits don't always show up immediately here if you use the GitHub web UI to get the local branch even with the upsteam one. It's not as fast as manually `git push`ing, maybe because it's new.

But looks like it's here 🥳 
https://github.com/tensorflow/docs/pull/1780/commits/246dd3378f02808b1ac9df958b2cfd13b3295ff1

**Comment by lamberta** [comment]
Hmm. Still a merge conflict ... even if I rebase locally. Looks like that needs to be reconciled

**Pull request closed without merging**
