### PR TITLE
KO: r2/guide/keras.ipynb

### PR DESCRIPTION
**Pull request by rickiepark**
Korean translation of r2/guide/keras.ipynb

### CODE REVIEW

**Comment by rickiepark** [comment]
I translated ko/r2/guide/keras/overview.ipynb.
And I added a section in README.md for new contributors.
Running with Colab is OK.
Thanks.

**Comment by lamberta** [comment]
Very nice.
@dynamicwebpaige is revamping the [community contributors](https://github.com/tensorflow/docs/tree/master/site/en/community/contribute) section. Still a work in progress, but might be worth linking here.
And it might be good place to include a note or two about the community translation process (and I welcome any ideas you have for this).

I'll merge this PR, but just something to think about :)

**Comment by rickiepark** [comment]
@lamberta , Can I add more commits in this PR for 5e9828f9dedac72bae702fe7605b445a5aef30b1?

**Comment by lamberta** [comment]
Sure! I think there's a way to mark a PR as a work in progress.
Sorry, I'm moving very fast now 😬

**Comment by rickiepark** [comment]
Thanks a lot!
I just pushed overview.ipynb. :)

**Comment by lamberta** [comment]
Nice!

**Pull request merged**
