### PR TITLE
it - add maryggiannella to reviewers

### PR DESCRIPTION
**Pull request by maryggiannella**
Hi everyone I would like to contribute to the translation of the TensorFlow documentation to Italian, so I add myself as reviewer :)

### CODE REVIEW

**Comment by lamberta** [comment]
Thank you for volunteering, @maryggiannella 
Please double check that you've signed the CLA: https://cla.developers.google.com/

Also, we recently created a docs-it@tensorflow.org group to help the community coordinate, please join: https://groups.google.com/a/tensorflow.org/g/docs-it

Ref: https://www.tensorflow.org/community/contribute/docs#community_translations

**Comment by maryggiannella** [comment]
@googlebot I signed it!

**Comment by maryggiannella** [comment]
Hi @lamberta, thank you very much ^^ 
ok, I will join the docs-it@tensorflow.org group. 
Thank you also for the documentation.

**Comment by maryggiannella** [comment]
Hi again
I have tried to open this link https://groups.google.com/a/tensorflow.org/g/docs-it but it gives me a 404, is it normal?

**Comment by lamberta** [comment]
Hmm, try: https://groups.google.com/a/tensorflow.org/forum/#!forum/docs-it

**Comment by maryggiannella** [comment]
Thank you so much @lamberta . I could open the new link and join the group.  ^^

**Pull request merged**
