### PR TITLE
Corrected some spelling and grammar errors

### PR DESCRIPTION
**Pull request by JoshEZiegler**

### CODE REVIEW

**Comment by JoshEZiegler** [comment]
@googlebot I signed it!

**Comment by lamberta** [comment]
@JoshEZiegler Were you able to sign the CLA at https://cla.developers.google.com/ ?

**Comment by JoshEZiegler** [comment]
Yep sorry I forgot to fill a field. Should be good now? @googlebot I signed it

**Comment by lamberta** [comment]
Got it—thanks
You should be good for future PRs, too

**Comment by lamberta** [comment]
Thanks. Moved to https://github.com/tensorflow/docs/pull/1175 to fix merge conflict

**Pull request closed without merging**
