### PR TITLE
Made some changes in Basic.ipynb ( interactive notebook for tensorflow introduction)

### PR DESCRIPTION
**Pull request by 15IITian**

### CODE REVIEW

**Comment by MarkDaoust** [comment]
Hi, please clear the outputs to make the diff easier to review.

**Comment by 15IITian** [comment]
Thank you for your reply .
I will surely clear the outputs in it :)

**Comment by MarkDaoust** [comment]
Thanks.

Looking at the actual changes I see that most of them are neutral or incorrect. It would be a net negative to merge this as is. So I'm closing, sorry!

**Comment by MarkDaoust** [comment]
@8bitmp3 - can you double check this one.

**Pull request closed without merging**
