### PR TITLE
Update pip.html

### PR DESCRIPTION
**Pull request by ymodak**
Updated python 3.9 and TF version compatibility
fixes https://github.com/tensorflow/tensorflow/issues/49295

### CODE REVIEW

**Comment by lamberta** [comment]
Thanks. Can you search "3.8" in the `/install/` directory for other replacements? I think `/install/_index.yaml` might also need an update.

**Review by MarkDaoust — DISMISSED** [review]
Confirmed 3.9 packages are available: https://pypi.org/project/tensorflow/#files

**Comment by 8bitmp3** [comment]
Thank you @ymodak

**Comment by ymodak** [comment]
Closing in the light of https://github.com/tensorflow/tensorflow/issues/49295#issuecomment-845419454
Thanks!

**Pull request closed without merging**
