### PR TITLE
Inceptionv3-transferlearning-with-lfw-dataset (reopened)

### PR DESCRIPTION
**Pull request by Siddhu2502**
Transfer Learning with TensorFlow's Inception v3 model using transfer learning on stunning colored images from the vast LFW people dataset! 🚀

### CODE REVIEW

**Comment by MarkDaoust** [comment]
See comments on https://github.com/tensorflow/docs/pull/2249.

**Comment by Siddhu2502** [comment]
i will do as said ... can you give me 2 days of time please ?

**Comment by Siddhu2502** [comment]
image

could you please help me fix this

**Comment by Siddhu2502** [comment]
@MarkDaoust please check now updated everything all according to that thing now if any changes are there please do say to me thanks

image

**Comment by Siddhu2502** [comment]
@MarkDaoust please check out i have done the checks necessary

**Comment by Siddhu2502** [comment]
@jmhodges @djones @alextp @MarkDaoust anyone please review it ... i have made the necessary checks anything further more to add or remove ?

**Comment by MarkDaoust** [comment]
Hi, it's not about the automated checks. See @8bitmp3's comment:

```
Thank you for your contribution. To make external contributions to docs with examples, 
check out the keras.io/examples repo (https://github.com/keras-team/keras-io/tree/master/examples).
Do make sure you're not duplicating any existing examples by replicating something with a different 
dataset. And please use the most up-to-date APIs.
```

He was trying to point out that while this is a nice tutorial:

1. User submitted examples go better in the keras examples collection.
2. There are already plenty of image-classification fine tuning examples.
3. The tutorial uses a few deprecated APIs:
    * ImageDataGenerator - prefer `keras.utils.image_dataset_from_directory`  
    * keras.applications - perfer `keras_cv` anywhere there's overlap.
    * InceptionV3 is an old architecture.

Also: 

- generally we can't use public figures in our examples (without permission).
- why are you trying to put it in the v1 directory?

So thanks, but we are not going to accept this PR.

**Pull request closed without merging**
