### PR TITLE
Update pandas_dataframe.ipynb

### PR DESCRIPTION
**Pull request by sushreebarsa**
'to each' was repeated for two times, so updated the doc from 'to each to each' to 'to each'.

### CODE REVIEW

**Comment by MarkDaoust** [comment]
Hi, thanks for the fixes.

Could you put these all in one PR? That will make the merge process much easier.

**Comment by 8bitmp3** [comment]
@sushreebarsa Let me assist you here

**Review by 8bitmp3 — APPROVED** [review]
Added more fixes

**Review by jojorgeluisrdz198 — COMMENTED** [review]
Account

**Comment by jojorgeluisrdz198** [comment]
Acepto

**Comment by jojorgeluisrdz198** [comment]
Jorge

**Pull request merged**
