### PR TITLE
switch to venv for virtual environment

### PR DESCRIPTION
**Pull request by grasskin**
Change install instructions and mentions of virtualenv to use venv.

@mihaimaruseac

### CODE REVIEW

**Comment by MarkDaoust** [comment]
OMG: 

https://twitter.com/drjtwit/status/1265561379253207042
https://www.liquidweb.com/kb/how-to-setup-a-python-virtual-environment-on-ubuntu-18-04/

**Comment by lamberta** [comment]
Yeah, we explicitly mention support for "Ubuntu 16.04 or later" so these commands should run as listed and assume that.

Is `venv` pip-installable or do we need to install the Ubuntu package `python3-venv`? (I generally dislike relying on the distro packages because they're often out-of-date).

**Comment by grasskin** [comment]
I couldn't find any mentions of it being pip-installable unfortunately, it seems users on certain Ubuntu will have to install it via apt-get

**Comment by grasskin** [comment]
Confirmed ubuntu 18.04 does not have venv installed

**Comment by lamberta** [comment]
Thanks for the update!

**Pull request merged**
