### PR TITLE
Update REVIEWERS

### PR DESCRIPTION
**Pull request by duanw0916**

### CODE REVIEW

**Comment by lamberta** [comment]
Hi @duanw0916, I don't like adding reviewers to this file unless they opt-in themselves.
Also, please sign the CLA: https://cla.developers.google.com/ 

@JayYip @wind2esg @loveunk @yantaozhao Can you confirm you'd like to be added to this REVIEWERS file (and get all the pull request notifications)?
Or can you send you a pull request for your own username by editing this file: https://github.com/tensorflow/docs/blob/master/site/zh-cn/REVIEWERS

Thanks

**Comment by Wind2esg** [comment]
Thank you @duanw0916.Thank you @lamberta for your friendly reminder. 
My pleasure to join the TF Community Localization.
I've singed the CLA and sent the pull request #734

**Comment by duanw0916** [comment]
@lamberta oh, sorry.

I would notify our Reviewers individually to sign the CLA and then send their own PR to update the file.

Thanks.

**Comment by lamberta** [comment]
Looks like all the individual PRs are in flight so closing this one.
Thanks, Wei and everyone!

**Pull request closed without merging**
