### PR TITLE
replace deprecated model.get_losses_for call by model.losses in migration guide

### PR DESCRIPTION
**Pull request by DorianKodelja**
See issue https://github.com/tensorflow/tensorflow/issues/43341

### CODE REVIEW

**Comment by DorianKodelja** [comment]
@googlebot I signed it!

**Comment by DorianKodelja** [comment]
@googlebot I fixed it.

**Comment by DorianKodelja** [comment]
@lamberta Hi, I'm contacting you since you're among the requested reviewers:
The linting test failed on part of the migration guideline that I didn't modify. 
Should I fix it in the same PR or create a separated issue for these ?
In the first case, i'm not sure how to replace "Native" and replacing "We" by "you"  doesn't feel right either

**Comment by MarkDaoust** [comment]
@tomerk, @omalleyt12 : Replacing `get_losses_for` with `.losses` in a custom estimator `model_fn`, is this change correct?

**Comment by tomerk** [comment]
This isn't a safe change to make. Estimators w/ custom model_fn's are generally pretty disrecommended, and basically use tf1 graphs/are in a deprecated-ish state. As such, they'll only work w/ the deprecated tf1-style methods especially when it comes to things like capturing losses.

Maybe this is something that should be made explicitly clearer in the migration guide? "Here's how you can use keras in an estimator for transitional migration purposes, but you really shouldn't be using estimators w/ custom model_fns anyway"?

**Comment by MarkDaoust** [comment]
Thanks @tomerk.

@DorianKodelja, can you make that change instead?

**Comment by MarkDaoust** [comment]
I'm sending a fix for that.

**Pull request closed without merging**
