### PR TITLE
Update bib.md

### PR DESCRIPTION
**Pull request by nitinsharda**
Grammatical correction.

### CODE REVIEW

**Comment by nitinsharda** [comment]
Infosys Corporate CLA is signed.

**Comment by nitinsharda** [comment]
I signed it!

**Comment by lamberta** [comment]
Can you try signing the CLA again here: https://cla.developers.google.com/
CLAbot seems to be having some issues 🤖

**Comment by nitinsharda** [comment]
> Can you try signing the CLA again here: https://cla.developers.google.com/
> CLAbot seems to be having some issues

Please find below the details of CLA.
Google group: InfosysContributors@googlegroup.com , CCLA has been signed by Gautam Khanna.

**Comment by nitinsharda** [comment]
I signed it again !! Let me know the next steps.

**Pull request merged**
