### PR TITLE
Add a reference to our Governance

### PR DESCRIPTION
**Pull request by bhack**
We could move or refactoring that later

### CODE REVIEW

**Comment by ewilderj** [comment]
If we're touching this page, definitely needs an update. the SIG list is badly outdated :(

**Comment by bhack** [comment]
Yes we know:
-  We are and we could go out of sync with mailing-lists.md
- SIGS list is outdated vs SIGS folders in community
- No Gitter links

But in the meantime I think that it is better to have a connection to our Contribution Governance with this PR so that it will easier to review what we want to do with this page as whole later.

**Comment by theadactyl** [comment]
I think we want to move the file this refers to to the website, though?

**Comment by theadactyl** [comment]
Agreed that this page also needs a refresh (or removal). I will assign to
myself to propose a direction when I'm back from vacation.

**Review by lamberta — APPROVED** [review]
Sounds like there's future work on the way but this is worth merging now. Thanks

**Comment by theadactyl** [comment]
@bhack can you assign me a bug for updating the content?

**Comment by bhack** [comment]
>  @bhack can you assign me a bug for updating the content?

I don't have this "power" on the repository. I can mention you but probably it is not the same for tracking.

**Comment by theadactyl** [comment]
That works -- I'll assign to myself

**Pull request merged**
