### PR TITLE
1st draft of keras feature columns

### PR DESCRIPTION
**Pull request by eganjam**
working with Josh, Karmel and Mark on this tutorial

### CODE REVIEW

**Comment by random-forests** [comment]
Okay! Made some updates to the code based on Mark's suggestions, and showed how to demo the feature columns as we create them. On the TODO list:

* Replace the census data w/ something else.
* Add textual descriptions of the various columns.
* Add next steps

Will take a swing at that in the next few days.

**Comment by eganjam** [comment]
I signed it!

**Comment by MarkDaoust** [comment]
It's okay cla-bot (the other user is a googler).

Let's just do any finalization in the merge.

**Comment by lamberta** [comment]
Mark is working on this internally to get it to work: cl/231683187

**Comment by random-forests** [comment]
Hey James! Long time. You rock / thanks again so much for doing this. Bugs all fixed up, and (since time flies!) will make a version of this tutorial for 2.0. Will close this PR out (content for the new tutorial will be basically the same, just many minor changes do easier to start fresh).

**Comment by eganjam** [comment]
Hi Josh, long time is right!
Had a look at cl/231683187 and it looks great.
Defo keen to see the 2.0 update too.

**Pull request closed without merging**
