### PR TITLE
[id] Add Keras notebook translations and update REVIEWERS

### PR DESCRIPTION
**Pull request by csahat**
add my GitHub id

### CODE REVIEW

**Comment by lamberta** [comment]
Thank you!
Staged here on Colab:
* https://colab.research.google.com/github/csahat/docs/blob/patch-4/site/id/tutorials/keras/classification.ipynb
* https://colab.research.google.com/github/csahat/docs/blob/patch-4/site/id/tutorials/keras/text_classification.ipynb

**Comment by lamberta** [comment]
Would @febriaroo or @isfaaghyth be able to review these two notebooks?
(And please add yourself to the [site/id/REVIEWERS](https://github.com/tensorflow/docs/blob/master/site/id/REVIEWERS) to get notified of new pull requests to the `site/id` directory.) Thank you!

**Comment by csahat** [comment]
> @csahat Please update the readme.md for the english words that we're not translate to english. rather than that, it's LGTM..
> Thank you for your contribution!

Sorry, what did you mean English words that not translate to English?

**Comment by csahat** [comment]
@febriaroo Sorry what did you mean by "English words that we're not translate to English"

**Comment by febriaroo** [comment]
Sorry! I mean we're not translating to Bahasa.. We need to make all the
document consistent :)

**Comment by csahat** [comment]
@lamberta I think it is better for me to create new pull request then?

**Pull request closed without merging**
