### PR TITLE
KO: translate ko/r2/tutorials/keras/feature_columns.ipynb

### PR DESCRIPTION
**Pull request by rickiepark**
Korean translation of ko/r2/tutorials/keras/feature_columns.ipynb

### CODE REVIEW

**Comment by rickiepark** [comment]
KO Translation of feature_columns.ipynb.
Running on Colab is OK.
Thanks!

**Comment by lamberta** [comment]
And, if you want, you can just update `ko/README.md` and I can copy/paste the note across notebooks since I know that can be a pain :)

**Comment by rickiepark** [comment]
Sure, I’ll make other PR for that. 
But I don’t want your pain. :)

**Comment by rickiepark** [comment]
Remove https://bit.ly/tf-translate link. Thanks :)

**Comment by rickiepark** [comment]
I move feature_columns.ipynb to alpha folder and change a term to common word in disclaimer.
Thanks! :)

**Pull request merged**
