### PR TITLE
Fix 'output_shape' error in Text classification tutorial

### PR DESCRIPTION
**Pull request by toaomalkster**
AttributeError: '_OptionsDataset' object has no attribute 'output_shapes'.

Following recommendations here:
https://github.com/tensorflow/datasets/issues/102
https://github.com/tensorflow/tensorflow/issues/28669

### CODE REVIEW

**Comment by toaomalkster** [comment]
@googlebot I signed it!

**Comment by yashk2810** [comment]
This is being fixed by a more permanent solution.

@MarkDaoust has a fix for it that is in flight.

**Comment by yashk2810** [comment]
Thanks for the PR!

**Comment by RitikGupta9125** [comment]
Is there any update related to fixing of the problem.

**Pull request closed without merging**
