### PR TITLE
Add plotting lines in regression tutorial, add notebook versions of non-ml examples

### PR DESCRIPTION
**Pull request by bkmgit**

### CODE REVIEW

**Comment by bkmgit** [comment]
Add notebook version of Mandelbrot

**Comment by bkmgit** [comment]
Add notebook version of PDES

**Comment by lamberta** [comment]
Staging for new notebooks:
* https://colab.research.google.com/github/bkmgit/docs-1/blob/master/site/en/tutorials/non-ml/mandelbrot.ipynb
* https://colab.research.google.com/github/bkmgit/docs-1/blob/master/site/en/tutorials/non-ml/pdes.ipynb

**Comment by bkmgit** [comment]
Thanks. Any more details available on why Ubuntu sanity check fails?

**Comment by kokoro-team** [comment]
It looks like this is a build script (user) failure.  There's a message about using "we" in the docs instead of "you".  There's at least one instance of "we" in the few commits I looked at, so maybe try fixing that?

(Instead of saying "we will add this later", say "this will be added later")

**Comment by lamberta** [comment]
Awesome. Thanks, Benson, for those fixes.

**Pull request merged**
