### PR TITLE
fix save_and_serialize.ipynb

### PR DESCRIPTION
**Pull request by beginner30**
duplicated word "for Sequential models" in sentence

### CODE REVIEW

**Comment by beginner30** [comment]
@googlebot I fixed it.

**Comment by beginner30** [comment]
@googlebot I consent

**Comment by beginner30** [comment]
@googlebot I consent.

**Comment by beginner30** [comment]
It is my first pull request.
If i missed something, please comment.

**Comment by MarkDaoust** [comment]
Hi beginner30, 

Usually when the bot does this it's because the email address in the commits is not the same as the email address on the github account.

Check your `$ git config user.email`, and be sure you have the same one set in your github account settings. 

Use `$ git config --global user.email johndoe@example.com` to set it.

See this article for more about how these commands work: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup

**Pull request closed without merging**
