### PR TITLE
Corrected a sentence

### PR DESCRIPTION
**Pull request by jvishnuvardhan**
Corrected a sentence from "predict some housing prices" to "predict fuel efficiency"

### CODE REVIEW

**Comment by rthadur** [comment]
CLA looks good , but it is not reflecting here

**Comment by lamberta** [comment]
This PR needs @jvishnuvardhan to sign the CL.
Is there another pull request you can point me to shows this?

**Comment by rthadur** [comment]
> This PR needs @jvishnuvardhan to sign the CL.
> Is there another pull request you can point me to shows this?

Sorry i was mentioning about @jvishnuvardhan  CLA , I checked here https://signcla.corp.google.com/search?q=jvishnuvardhan+&cla=google

**Comment by lamberta** [comment]
sounds good.
I think GoogleBot needs to see: I signed it!
I'll manually switch it and hopefully the bot works next time.

**Pull request merged**
