### PR TITLE
R2.0rc I meet an error during i run feature_columns.ipynb

### PR DESCRIPTION
**Pull request by shazhongcheng**
During my run test in [feature_columns.ipynb](https://github.com/tensorflow/docs/blob/r2.0rc/site/en/r2/tutorials/keras/feature_columns.ipynb)

I meet an error when i run the code:
```python
crossed_feature = feature_column.crossed_column([age_buckets, thal], hash_bucket_size=1000)
demo(feature_column.indicator_column(crossed_feature))
```

the error is
```python
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-44-2e886231773b> in <module>
      1 crossed_feature = feature_column.crossed_column([age_buckets, thal], hash_bucket_size=1000)
----> 2 demo(feature_column.indicator_column(crossed_feature))

<ipython-input-38-a363fff703dc> in demo(feature_column)
      3 def demo(feature_column):
      4     feature_layer = layers.DenseFeatures(feature_column)
----> 5     print(feature_layer(example_batch).numpy())

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    889           with base_layer_utils.autocast_context_manager(
    890               self._compute_dtype):
--> 891             outputs = self.call(cast_inputs, *args, **kwargs)
    892           self._handle_activity_regularization(inputs, outputs)
    893           self._set_mask_metadata(inputs, outputs, input_masks)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\feature_column\dense_features.py in call(self, features, cols_to_output_tensors)
    131       with ops.name_scope(column.name):
    132         tensor = column.get_dense_tensor(transformation_cache,
--> 133                                          self._state_manager)
    134         processed_tensors = self._process_dense_tensor(column, tensor)
    135         if cols_to_output_tensors is not None:

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\feature_column\feature_column_v2.py in get_dense_tensor(self, transformation_cache, state_manager)
   4355     # Feature has been already transformed. Return the intermediate
   4356     # representation created by transform_feature.
-> 4357     return transformation_cache.get(self, state_manager)
   4358 
   4359   @deprecation.deprecated(_FEATURE_COLUMN_DEPRECATION_DATE,

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\feature_column\feature_column_v2.py in get(self, key, state_manager)
   2606     column = key
   2607     logging.debug('Transforming feature_column %s.', column)
-> 2608     transformed = column.transform_feature(self, state_manager)
   2609     if transformed is None:
   2610       raise ValueError('Column {} is not supported.'.format(column.name))

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\feature_column\feature_column_v2.py in transform_feature(self, transformation_cache, state_manager)
   4294     """
   4295     id_weight_pair = self.categorical_column.get_sparse_tensors(
-> 4296         transformation_cache, state_manager)
   4297     return self._transform_id_weight_pair(id_weight_pair)
   4298 

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\feature_column\feature_column_v2.py in get_sparse_tensors(self, transformation_cache, state_manager)
   4146     """See `CategoricalColumn` base class."""
   4147     return CategoricalColumn.IdWeightPair(
-> 4148         transformation_cache.get(self, state_manager), None)
   4149 
   4150   @deprecation.deprecated(_FEATURE_COLUMN_DEPRECATION_DATE,

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\feature_column\feature_column_v2.py in get(self, key, state_manager)
   2606     column = key
   2607     logging.debug('Transforming feature_column %s.', column)
-> 2608     transformed = column.transform_feature(self, state_manager)
   2609     if transformed is None:
   2610       raise ValueError('Column {} is not supported.'.format(column.name))

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\feature_column\feature_column_v2.py in transform_feature(self, transformation_cache, state_manager)
   4107         inputs=feature_tensors,
   4108         num_buckets=self.hash_bucket_size,
-> 4109         hash_key=self.hash_key)
   4110 
   4111   @deprecation.deprecated(_FEATURE_COLUMN_DEPRECATION_DATE,

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\ops\sparse_ops.py in sparse_cross_hashed(inputs, num_buckets, hash_key, name)
    595       num_buckets=num_buckets,
    596       hash_key=hash_key,
--> 597       name=name)
    598 
    599 

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\ops\sparse_ops.py in _sparse_cross_internal(inputs, hashed_output, num_buckets, hash_key, name)
    648       out_type=out_type,
    649       internal_type=internal_type,
--> 650       name=name)
    651 
    652   return sparse_tensor.SparseTensor(indices_out, values_out, shape_out)

~\AppData\Roaming\Python\Python36\site-packages\tensorflow_core\python\ops\gen_sparse_ops.py in sparse_cross(indices, values, shapes, dense_inputs, hashed_output, num_buckets, hash_key, out_type, internal_type, name)
   1148         shapes, dense_inputs, "hashed_output", hashed_output, "num_buckets",
   1149         num_buckets, "hash_key", hash_key, "out_type", out_type,
-> 1150         "internal_type", internal_type)
   1151       _result = _SparseCrossOutput._make(_result)
   1152       return _result

SystemError: <built-in function TFE_Py_FastPathExecute> returned a result with an error set
```
it seems that some parameters overflow, but i do'nt chang any codes.
I try to change the pandas's dtype form int64 an float64 to float32, but it doesn't work.
Doesn't it really wrong, or i do something wrong?

### CODE REVIEW

**Comment by lamberta** [comment]
Hi xiaosha@,
I think this bug was fixed in the latest TF2 RC. FIles are moving around as we prepare for the TF2-first site switch. That notebook should be fixed: https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb
Let me know if you run into this error in the latest. Thanks

**Comment by shazhongcheng** [comment]
> Hi xiaosha@,
> I think this bug was fixed in the latest TF2 RC. FIles are moving around as we prepare for the TF2-first site switch. That notebook should be fixed: https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb
> Let me know if you run into this error in the latest. Thanks

ok i really thanks for your reply , i will test in following day！

**Comment by shazhongcheng** [comment]
> > Hi xiaosha@,
> > I think this bug was fixed in the latest TF2 RC. FIles are moving around as we prepare for the TF2-first site switch. That notebook should be fixed: https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb
> > Let me know if you run into this error in the latest. Thanks
> 
> ok i really thanks for your reply , i will test in following day！

It seems strange that i don`t receive any emails. I am so sorry for my too later emails.

**Comment by shazhongcheng** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Comment by shazhongcheng** [comment]
> xiaosha @您好，
> 我认为此错误已在最新的TF2 RC中修复。在为TF2优先站点切换做准备时，文件正在四处移动。该笔记本应该是固定的：[https](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb) : [//colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb](https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/structured_data/feature_columns.ipynb)
> 让我知道您是否在最新。谢谢

Hello! I try it twice, and it doesn`t. This time, i try more operations. But still meet this OverflowError.
```
OverflowError                             Traceback (most recent call last)
OverflowError: Python int too large to convert to C long
``` 
It run error on:
```
crossed_feature = feature_column.crossed_column([age_buckets, thal], hash_bucket_size=1000)
# I change the original code   demo(feature_column.indicator_column(crossed_feature)) 
# to show this error
layers.DenseFeatures(feature_column.indicator_column(crossed_feature))(example_batch)
```
I still don`t why. It is so strange , because even i cast the type from int32 to float32, it still run error.
My computer is win64, and my python is python3.6.

**Pull request closed without merging**
