### PR TITLE
KO: update ko/alpha/guide/migration_guide.ipynb

### PR DESCRIPTION
**Pull request by rickiepark**
Update for improving translation.
Thanks!

### CODE REVIEW

**Comment by cre8tor** [comment]
@lamberta Can I review it? I want to approve it because it has been reviewed already.
@rickiepark I've read all of the comments you left and found it your translation is thoughtful. Please don't hesitate to guide my translation. And I've never contributed before, so if I make some mistakes (including manners) please let me know about them. Maybe I should ask your understanding in advance.

**Comment by lamberta** [comment]
Thank you, @rickiepark and @cre8tor.

Unfortunately, the GitHub UI does not allow me to assign arbitrary *Reviewers* or *Assignees* to a PR since it seems they must be in a GitHub team associated with the repo/org (which is pretty annoying). Since I can't maintain this kind of team, I'm working on a more automated solution using the docs-ko@tensorflow.org list which you can opt-in to: https://groups.google.com/a/tensorflow.org/forum/#!forum/docs-ko

Weirdly, you can still "review" a CL without being assigned, just click: Files changed > Review changes > Approve (with message)
You won't be able to merge but at least gives me a signal the translation is good enough. Or just give me a thumbs up or something in the comments. Basically I'm just looking for a way to not have to ask "is this ready?" on every translation PR :)

**Comment by rickiepark** [comment]
Thank you @cre8tor. Don't worry about the manner. You are already good person to help others. :)

**Comment by cre8tor** [comment]
@lamberta Thank you very much for kind explanation 👍 
@rickiepark It's very nice of you to say so 😄

**Pull request merged**
