### PR TITLE
KO: ko/README.md not-to-translate term fix

### PR DESCRIPTION
**Pull request by JKIsaacLee**
Summary : removed not-to-translate term "import"(가져오기)

in #808, 'import' is able to translate '가져오기', but he is hesitating to change the word.
From this PR, I suggest to remove 'import'.
Thanks. 👍

### CODE REVIEW

**Comment by rickiepark** [comment]
Thank you, @JKIsaacLee 

Could you please introduce the glossary spreadsheet and add the link(http://bit.ly/tf-docs-translation-glossary)? :)

**Comment by JKIsaacLee** [comment]
> Thank you, @JKIsaacLee
> 
> Could you please introduce the glossary spreadsheet and add the link(http://bit.ly/tf-docs-translation-glossary)? :)

I introduced it. Thank you. 👍

**Comment by rickiepark** [comment]
Thanks a lot. LGTM 👍

**Comment by Choiuijin1125** [comment]
LGTM :) 👍

**Pull request merged**
