### PR TITLE
fixed broken links on distribute/custom_training

### PR DESCRIPTION
**Pull request by luke-han**
fixed broken links

### CODE REVIEW

**Comment by lamberta** [comment]
Thank you.

Community translations are now located in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo (see [this message](https://groups.google.com/a/tensorflow.org/g/docs/c/GJPq7S_fw4c/m/lA1qfBX2EQAJ) for context).

I'll move over/duplicate existing pull requests as I find time. In the meantime, please feel free to create a new pull request in that repo 😀 Then you can close this PR and add a link to the new one.

**Comment by luke-han** [comment]
Hi @lamberta 

I moved the changes on community translations to https://github.com/tensorflow/docs-l10n/pull/2.

I modified this PR to fix broken links on en. Please review this PR.

Thanks

**Comment by lamberta** [comment]
Perfect—thank you!

**Comment by luke-han** [comment]
@lamberta

This modified PR fixes broken links on English version. 

Should I create new PR?

**Comment by lamberta** [comment]
Ah. Yes, either a new PR or remove the re-open this and remove the non-en/ files. Thanks

**Pull request closed without merging**
