### PR TITLE
Tutoruial on activation heatmaps with tf.keras

### PR DESCRIPTION
**Pull request by Mbah-Javis**
I have made a small tutorial on how activation heatmaps work with tf.keras so i thought it will be good if i submit it here as recommended by Sir @SayakPaul

### CODE REVIEW

**Comment by Mbah-Javis** [comment]
I didn't make any changes to <strong>tools/templates/notebook.ipynb</strong> its showing here because i run it in my branch and the tensorflow logo, colab, github logo and download images that were not visible on the notebook became visible :)

**Comment by sayakpaul** [comment]
Hi @lamberta. @Mbah-Javis participated in this year's GCI and I was one of the mentors there. He did a pretty decent job on this one hence I suggested this might be a good fit here.

**Comment by lamberta** [comment]
Thanks. Looks interesting and we'll take a look.
But might take a while to review since unsolicited docs typically require back-and-forth that makes it difficult to plan work and provide a good contributor experience. We're working on a better process and guidelines for community submissions and community reviews.

**Comment by lamberta** [comment]
Gave it a quick look and it has potential :)
But it would be helpful if the mentors and the community were able to review this first. There are a fair amount of writing issues that can be addressed by briefly looking over the [Google dev docs style guide](https://developers.google.com/style/highlights) and the [TensorFlow docs style guide](https://www.tensorflow.org/community/contribute/docs_style).

**Comment by sayakpaul** [comment]
@Mbah-Javis when could you start working on it?

**Comment by Mbah-Javis** [comment]
> @Mbah-Javis when could you start working on it?

@sayakpaul Sorry i couldn't work on this earlier for some reasons now am working on the changes

**Comment by Mbah-Javis** [comment]
@lamberta After taking a look at [ Google dev docs style guide](https://developers.google.com/style/highlights) and [TensorFlow docs style guide](https://www.tensorflow.org/community/contribute/docs_style), I made some changes to the tutorial like changing tf.keras to `tf.keras`, correcting grammatical errors  and many other things.

**Comment by Mbah-Javis** [comment]
Hello @lamberta the reviews are taking more time than I expected is this how it usually stays? If there will be anymore changes that need to be made please let me know.
Thank you  :)

**Comment by lamberta** [comment]
> more time than I expected is this how it usually stays?

Sorry, it's normal. Submissions to the official documentation must have multiple rounds of reviews for technical and editorial quality. We can't make time guarantees because it depends what folks are working on. Generally it's best to start with a proposal to the docs@tensorflow.org list before submitting a complete tutorial, since it will need work.

Usually we encourage submitting tutorials to the [examples/community](https://github.com/tensorflow/examples/tree/master/community/en) repo first, then we can look into bringing it in here.

**Comment by Mbah-Javis** [comment]
@lamberta okay thanks for your reply

**Comment by lamberta** [comment]
PR stalled but thanks.
For community contributions, best to engage with the TensorFlow SIGS: https://github.com/tensorflow/community/tree/master/sigs
Or the ML GDEs: https://github.com/ml-gde

**Comment by sayakpaul** [comment]
@lamberta currently, we only support TensorFlow Lite tutorials in this capacity and _nothing_ other than that.

**Pull request closed without merging**
