### PR TITLE
updated to reflect tensorrt  change for v2.1

### PR DESCRIPTION
**Pull request by saikiran2603**
tensorrt version 6.0.1 is needed for v2.1 of tf as per error messages. modifying the command to reflect tensorrt 6.0.1

### CODE REVIEW

**Comment by saikiran2603** [comment]
signed it

**Comment by saikiran2603** [comment]
@googlebot I signed it!

**Comment by saikiran2603** [comment]
@googlebot I signed it!

**Comment by saikiran2603** [comment]
i am not sure if i should make the same change for Ubuntu 16.04 (CUDA 10) ? as for Ubuntu 16.04 (CUDA 9.0 for TensorFlow < 1.13.0) i see its already on a older version than v5 ..

**Comment by lamberta** [comment]
Thanks. We have a internal update pending for this page, lemme merge that first and then this after.

**Comment by saikiran2603** [comment]
Hey any update on this ?

**Comment by lamberta** [comment]
Hey Sai. Still waiting for 2.1 final to land before we update the official docs.

**Comment by saikiran2603** [comment]
Thanks @lamberta !!!

**Pull request merged**
