### PR TITLE
zh-CN: index.md

### PR DESCRIPTION
**Pull request by kjlintong**

### CODE REVIEW

**Comment by lamberta** [comment]
Thank you but index.md files are no longer required for ja, ko, and zh-cn.
This is part of [this announcement](https://groups.google.com/a/tensorflow.org/d/msg/docs-zh-cn/mhLp-egzNyE/EhGSeIBqAQAJ) but I see I neglected to add `index.md` files 😬Sorry!

For the install/ section, any *.yaml files (_book.yaml/_toc.yaml/_index.yaml), or index files for Japanese, Korean, or Chinese, we're using an internal team since it's easier to keep up to date and the content isn't technical (they have a difficult time with machine learning content and notebooks.)

Can we note this in the ja/, ko/, and zh-cn/ README files (or wherever the community looks for instructions? @rickiepark @ohtaman, @sfujiwara

Thank you!

**Comment by kjlintong** [comment]
@lamberta   It dosen't matter.:smile:

**Comment by rickiepark** [comment]
@lamberta , Ok I'll update README in ko folder.

**Comment by gaoljhy** [comment]
ok,close

**Pull request closed without merging**
