### PR TITLE
Updated saved_model.ipynb

### PR DESCRIPTION
**Pull request by aavishkarmishra**
### This pull request is created with respect to issue [#41679](https://github.com/tensorflow/tensorflow/issues/41679) of tensorflow repo

> Updated line 129-130 for **multiple GPU support**  

> Updated line 324 to handle tensorflow serving

### CODE REVIEW

**Comment by aavishkarmishra** [comment]
@lamberta  @yashk2810  @MarkDaoust  will you please review this PR

**Comment by aavishkarmishra** [comment]
Hii, @lamberta  @yashk2810 @MarkDaoust will you please review this PR

**Comment by yashk2810** [comment]
Have you tested it?

**Comment by lamberta** [comment]
Since this section is not executable code within the notebook, we should make the pieces clear so folks know what's going on when they copy/paste. Let's break it up a bit like:

```
model_base_path = mobilenet_save_path[:-3]  # Get model path from the temp directory.

nohup tensorflow_model_server \
  --rest_api_port=8501 \
  --model_name=mobilenet \
  --model_base_path="${model_base_path}" >server.log 2>&1
```

And, yes, please test and confirm. Thanks

**Comment by aavishkarmishra** [comment]
> Have you tested it?



> Since this section is not executable code within the notebook, we should make the pieces clear so folks know what's going on when they copy/paste. Let's break it up a bit like:
> 
> ```
> model_base_path = mobilenet_save_path[:-3]  # Get model path from the temp directory.
> 
> nohup tensorflow_model_server \
>   --rest_api_port=8501 \
>   --model_name=mobilenet \
>   --model_base_path="${model_base_path}" >server.log 2>&1
> ```
> 
> And, yes, please test and confirm. Thanks
I can make it executable in colab, as I have test it there and it is working.

**Comment by aavishkarmishra** [comment]
@yashk2810 @MarkDaoust I have added warning at the top, now please check and tell me if any problem occur ?

**Comment by aavishkarmishra** [comment]
@yashk2810 @MarkDaoust I have added warning at the top, now please check and tell me if any problem occur ?

**Comment by aavishkarmishra** [comment]
@yashk2810 @MarkDaoust Please review thus pull request !

**Comment by aavishkarmishra** [comment]
@MarkDaoust @yashk2810 Will you please consider reviewing this pull request.

**Review by MarkDaoust — DISMISSED** [review]
This works.

**Comment by MarkDaoust** [comment]
> If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA (login here to double check)?

@aavishkarmishra  it looks like a few of your commits used a different email address, can you fix it to make the CLA bot happy? Squashing this into a single commit with the right email address and force-pushing to this branch would work.

**Comment by lamberta** [comment]
I'll see if I can squash some commits here. there's no need to delete the file 😬

**Comment by lamberta** [comment]
Welp, I ran out of time on this. Will need to resolve the merge conflict before we can merge this PR

**Comment by aavishkarmishra** [comment]
@googlebot I fixed it.

**Comment by aavishkarmishra** [comment]
@googlebot I fixed it.

**Pull request merged**
