### PR TITLE
Update graph_optimization.ipynb for Intel Xeon 6 Processors

### PR DESCRIPTION
**Pull request by louie-tsai**
Intel Xeon 6 Processors also support fp16 with auto mixed precision optimizer

### CODE REVIEW

**Comment by 8bitmp3** [comment]
@MarkDaoust @markmcd

**Comment by MarkDaoust** [comment]
Hi @louie-tsai, I don't know anything about this.  Do you have any references showing that this is true?

**Review by Morehman27 — APPROVED** [review]

**Comment by louie-tsai** [comment]
> Hi @louie-tsai, I don't know anything about this. Do you have any references showing that this is true?

Thanks for asking.
Here are couple references for fp16 on the latest Xeon processors.
https://www.intel.com/content/www/us/en/content-details/669773/intel-avx-512-fp16-instruction-set-for-intel-xeon-processor-based-products-technology-guide.html
https://www.intel.com/content/www/us/en/newsroom/news/intel-unveils-future-generation-xeon.html#gs.g4yc8z

**Comment by MarkDaoust** [comment]
Cool, thanks. I see the processors have FP16. Does anyone know for sure that this actualy works with the `Auto mixed precision optimizer`?

**Comment by agramesh1** [comment]
> > Cool, thanks. I see the processors have FP16. Does anyone know for sure that this actualy works with the `Auto mixed precision optimizer`?
> 
> It works for AMP optimizer. Loop the Intel architect @agramesh1 for more comment if any.

Hi @MarkDaoust yes, it is now supported in TF and XLA.  We have been working with @penpornk to add support for fp16 AMP using the  AMX-FP16 that was introduced in the latest Intel Xeon CPUs.

**Review by MarkDaoust — APPROVED** [review]

**Comment by MarkDaoust** [comment]
Cool thanks!

**Comment by louie-tsai** [comment]
@markmcd 
possible to help review and approve the PR?
thanks!

**Comment by markmcd** [comment]
> @markmcd possible to help review and approve the PR? thanks!

Done - copybara will merge shortly.

**Pull request merged**
