### PR TITLE
Update checkpoint.ipynb

### PR DESCRIPTION
**Pull request by bdevnani3**
Small typo fix

### CODE REVIEW

**Comment by bdevnani3** [comment]
@googlebot I signed it!

**Comment by lamberta** [comment]
Thanks, @bdevnani3 
Not seeing your CLA, can you try clicking through this page again? https://cla.developers.google.com/ 
Thanks

**Comment by bdevnani3** [comment]
Hmm, I'm quite confused why this is failing :/

Screen Shot 2019-10-21 at 11 11 34 AM

**Comment by bdevnani3** [comment]
Any ideas @lamberta?

**Comment by lamberta** [comment]
Hmm. Looks like your git commit is using your gmail address and confusing the bot. Can you sign with that address? Or, may want to update your .gitconfig

**Comment by bdevnani3** [comment]
@googlebot I signed it!

**Comment by bdevnani3** [comment]
Ah, thanks for the tip. Done! @lamberta

**Pull request merged**
