### PR TITLE
Formatting the code snippet

### PR DESCRIPTION
**Pull request by Abhishek01039**
fixes https://github.com/tensorflow/tensorflow/issues/45777

### CODE REVIEW

**Comment by Abhishek01039** [comment]
Hello @yashk2810 
can you please review this PR?
Thanks

**Comment by lamberta** [comment]
Thanks, but I don't think this patch fixes the formatting issue in https://github.com/tensorflow/tensorflow/issues/45777. cc: @yashk2810

**Comment by Abhishek01039** [comment]
Hello @yashk2810 
can you please have a look into this?
Thanks

**Comment by lamberta** [comment]
Thanks but this isn't the fix for https://github.com/tensorflow/tensorflow/issues/45777. Will likely need to edit the docstring and not the doc generator tool.

**Comment by Abhishek01039** [comment]
Ah, Thanks @lamberta

**Pull request closed without merging**
