### PR TITLE
modify pyplot keys

### PR DESCRIPTION
**Pull request by LittileZiggs**
the keys of the plt are wrong, they should not be history.history['accuracy'] and history.history['val_accuracy'].  They should be history.history['acc'] and history.history['val_acc'] instead.

### CODE REVIEW

**Comment by LittileZiggs** [comment]
> @googlebot I signed it!

**Comment by lamberta** [comment]
Thanks, but your notebook breaks in Colab (see link from tfdocsbot above). Make sure you are using TF2.
The current TF2 notebook works: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/cnn.ipynb

**Comment by LittileZiggs** [comment]
> Thanks, but your notebook breaks in Colab (see link from tfdocsbot above). Make sure you are using TF2.
> The current TF2 notebook works: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/cnn.ipynb

Thank you. I previously run the codes in TF1.14, keys should be 'acc' and 'val_acc'. After I upgraded to TF2, keys should be altered to 'accuracy' and 'val_accuracy', or it would crash. It seems that the docs are based on TF2 instead of TF1.14.

**Comment by lamberta** [comment]
Thanks. Yes, we recently switched everything over to TF2-first 😀

TF 1.x docs are archived in the `r1/` directory (GitHub only): https://github.com/tensorflow/docs/tree/master/site/en/r1

**Pull request closed without merging**
