### PR TITLE
Fix variable name

### PR DESCRIPTION
**Pull request by rickiepark**
`img_inputs` is not used in this notebook.
I think it must be `inputs`. :)
Thanks.

### CODE REVIEW

**Comment by lamberta** [comment]
Hi Haesun,

I think this is intentional since the previous line says: "For an input meant for images .... we would have used" ---meaning not for this example.

Maybe we can just add a code comment to make it clearer this block is just an example and not used?

**Comment by rickiepark** [comment]
Oops sorry, I didn't see the line.
`inputs = keras.Input(shape=(784,))`
I knew that `inputs` is not defined. :(

Yes, adding comment is good idea.
How about the following?
```
# just for illustration purposes
img_inputs = keras.Input(shape=(32, 32, 3))
```

**Comment by lamberta** [comment]
Sorry for the delay, Haesun. Yes, I think that comment would be a good addition

**Comment by rickiepark** [comment]
Thanks @lamberta ,
I added a comment. :)

**Pull request merged**
