### PR TITLE
Upgrade Java installation guide to 0.3.1

### PR DESCRIPTION
**Pull request by karllessard**
Please merge this changes to reflect the installation guide to the latest release of TensorFlow Java (0.3.1)

Note: I was under the impression that I've already proposed changes in the main `/tensorflow/docs` for the preview 0.3.0 release but cannot find any trace of that. But if there is any, please ignore my previous request and only consider this new one instead.

CC\ @MarkDaoust

### CODE REVIEW

**Review by MarkDaoust — APPROVED** [review]

**Comment by karllessard** [comment]
Thanks @MarkDaoust . Now is there anything that needs to be done on our side to regenerate the [API documentation](https://www.tensorflow.org/api_docs/java/org/tensorflow/package-summary) for Java, or this needs to be handled on your end? [Link to the script](https://github.com/tensorflow/java/blob/master/tools/build_java_api_docs.py)

CC\ @craigacp

**Comment by MarkDaoust** [comment]
> Now is there anything that needs to be done on our side to regenerate the API documentation for

I'm running the update job. I'll let you know when that's up.

**Comment by MarkDaoust** [comment]
Hi Karl, 

That update is published.

**Comment by karllessard** [comment]
The Javadoc you mean? I still see the [old one](https://www.tensorflow.org/api_docs/java/org/tensorflow/package-summary), is it somewhere else?

**Comment by karllessard** [comment]
Ok I've logged in and now see the new classes [here](https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/package-summary#classes), but only those at the root level, a lot is missing. I'm on my phone though, I'll take a better look at it on my laptop later today.

**Comment by Craigacp** [comment]
I assume he means in the staging area - https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/package-summary. It looks like that's from at least 0.3.0. There weren't any visible docs changes in 0.3.1.

**Comment by Craigacp** [comment]
> Ok I've logged in and now see the new classes [here](https://www.tensorflow.org/jvm/api_docs/java/org/tensorflow/package-summary#classes), but only those at the root level, a lot is missing. I'm on my phone though, I'll take a better look at it on my laptop later today.

Everything looks like it's there for me (macOS , Chrome). They are just further down the left scrollbar.

**Pull request merged**
