### PR TITLE
Delete unnecessary semicolons

### PR DESCRIPTION
**Pull request by siyavash**
Found unnecessary semicolons in ipynb files.

### CODE REVIEW

**Comment by yashk2810** [comment]
If semicolon is not included, then this text gets printed "Text(0, 0.5, 'Sepal length')".

So, I think we need the semicolon.

**Comment by siyavash** [comment]
Oh, I didn't notice using semicolon in jupyter notebooks can suppress output of last line.
So, what's your suggestion ? 
Add plt.show() or close this PR ?
IMO, it's better to add plt.show(), because in other parts of tutorial plt.show() is used.

**Comment by yashk2810** [comment]
Adding plt.show() would work.

**Comment by lamberta** [comment]
Merged here: https://github.com/tensorflow/docs/commit/18dec2e29531b9fef26de3db8458af3ac8fe66ba

**Comment by siyavash** [comment]
I think this commit [eed8604](https://github.com/tensorflow/docs/pull/459/commits/eed8604f7240924c65aa9c978419f83efcbff382) is necessary, because in boosted_tree.ipnyb, plt.show() is used before importing.

**Comment by lamberta** [comment]
Yes, I see.
Once the 'ready to pull' label is applied the merge process has started for the PR. I'll create a separate PR for that last commit.

**Pull request closed without merging**
