### PR TITLE
KO : Deleted typo

### PR DESCRIPTION
**Pull request by dogemad**
Deleted "가능한"
thanks.

### CODE REVIEW

**Comment by rickiepark** [comment]
Hi @dogemad ,
Thanks for the contribution.

It's a typo, correct word is '가능한 한'.
But I'm not sure it must be removed.
How do you think? @cre8tor @Choiuijin1125 @JKIsaacLee

**Comment by JKIsaacLee** [comment]
In my opinion, if '가능한 한' will be removed, the translation might be required strict regulations. It can leads translators more restricted.
After the glossary is completed, if someone wants to remove that word, then I might be agree about that suggestion.
So, I think It's too early to remove that word.

**Comment by JKIsaacLee** [comment]
In e[en version upgrade.ipynb](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.ipynb), 'as seamless as possible' is included. I think it's correct translation.
Thanks to mentioning, @rickiepark .

**Comment by cre8tor** [comment]
@rickiepark Thank you for mentioning. I also think it OK to be removed.
@dogemad You should resolve CLA issue to merge this PR.

**Comment by dogemad** [comment]
@googlebot I signed it!

2019년 8월 14일 (수) 오후 6:00, Sung Il Kim <notifications@github.com>님이 작성:

**Comment by dogemad** [comment]
@googlebot I signed it!

2019년 8월 13일 (화) 오후 6:04, googlebot <notifications@github.com>님이 작성:

**Comment by dogemad** [comment]
resolved cla issue. thanks!

**Comment by cre8tor** [comment]
LGTM :+1:

**Comment by rickiepark** [comment]
Thasnk @cre8tor. How about waiting @Choiuijin1125 's opinion? :)

**Comment by Choiuijin1125** [comment]
Thank you for mentioning :) @rickiepark 
I think it's better to edit typo rather than deleting the word, because of as @JKIsaacLee mentioned, this word might be the author's intention. And I think it makes the sentence more meaningful :) thanks!

**Comment by rickiepark** [comment]
Thanks @Choiuijin1125 .
In fact this PR is not critical. But I want to hear from the reviewers.

@dogemad, Could you explain why do you think this word is removed rather than fixed? You opinion is much more important! :)

**Comment by dogemad** [comment]
The word “가능한한” or "가능한 한" in this sentence, unlike English, gives an unnatural feel. It is good to correct typos("가능한 한"), but in Korean, "옮겨가기 위해 ~ 를 개발하였습니다." I think that the term contains "가능한 한" to some extent.

**Comment by rickiepark** [comment]
Thank you @dogemad.
I agree that It can give some unnatural feel.

Do @JKIsaacLee , @Choiuijin1125 agree? :)

**Comment by JKIsaacLee** [comment]
In that sentence, using twice '그리고' makes korean sentence unnatural. I think it's more natural to replace one.

**Comment by dogemad** [comment]
@JKIsaacLee I added a commit to replace later "그리고" with "또한".

Thank you for your comment.

**Comment by Choiuijin1125** [comment]
Thanks for the ping :) @rickiepark 
Cool, go for it!!

**Comment by dogemad** [comment]
@rickiepark @Choiuijin1125 
Thank you for your decision, have a nice day! :D

**Comment by JKIsaacLee** [comment]
In my opinion, I suggest to restore '가능한 한'.
Thanks for your contribution.

**Comment by JKIsaacLee** [comment]
LGTM 👍

**Pull request merged**
