### PR TITLE
KO: translation ko/tutorials/eager/_style_transfer.ipynb

### PR DESCRIPTION
**Pull request by Choiuijin1125**
Start translate index.md, _style_transfer.ipynb 
I'm going to translate en/tutorials/eager
@rickiepark

### CODE REVIEW

**Comment by rickiepark** [comment]
Hi @Choiuijin1125 ,
Thanks for contribution!
Please exclude the files not related _style_transfer.ipynb.
If there are many files in a PR, it takes long time to review and merge to master branch. :)

**Comment by Choiuijin1125** [comment]
Thanks! @rickiepark 
I changed and I used force-pushed command so if there is a problem with synchronization, please tell me.
Thanks a lot!

**Comment by rickiepark** [comment]
Looks good.
If you have any question before request for review, feel free to post to [tensorflow-ko-docs](https://groups.google.com/forum/#!forum/tensorflow-ko-docs) groups in Korean. :)

**Comment by lamberta** [comment]
Thanks for this contribution.
FYI, any notebook that starts with an underscore is considered a work-in-progress and are not imported and displayed on tensorflow.org.
Mark has plans for this notebook but I think it needs a little bit updating. We can keep this PR around and see where this notebook lands in alpha/

**Comment by Choiuijin1125** [comment]
Thank you for mentioning @lamberta! I just finished translating this file.
Tell me if something wrong pleases, check out colab is okay. thanks!
 https://app.reviewnb.com/tensorflow/docs/pull/369/

**Comment by Choiuijin1125** [comment]
Sure I'll keep tracing version and update as soon as possible. thanks!

**Pull request merged**
