### PR TITLE
Removed Space from Filters in Tokenization

### PR DESCRIPTION
**Pull request by cr0wley-zz**
Since filter comes before split, adding ' ' (space) to the filters might create a problem. Hence we removed the space from the given filters to avoid such issue.

### CODE REVIEW

**Comment by cr0wley-zz** [comment]
@googlebot I signed it!

**Comment by lamberta** [comment]
Looks like the CI is failing. Please format notebooks with [nbfmt](https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/tools/) to get a readable diff. Thanks

```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs

$ python3 -m tensorflow_docs.tools.nbfmt notebook.ipynb
```

**Comment by cr0wley-zz** [comment]
@lamberta  thanks for the help!

**Comment by MarkDaoust** [comment]
It's okay bot, it's just me and 8bit.

**Review by 8bitmp3 — APPROVED** [review]
Hi @cr0wley-zz, thanks for the patience and nice work. We can indeed remove that extra space in `filter` as an unwanted text "character" in the `tf.keras.preprocessing.text.Tokenizer` class.

I also:
- Linted to pass the "second person" test ("we" -> "you", "our" -> "your"/"the").
- Formatted.
- Rebased, since there's been a lot of changes in the repo since you submitted the PR.

LGTM

**Comment by cr0wley-zz** [comment]
Hey @8bitmp3 thank you for the confirmation!

**Pull request merged**
