### PR TITLE
Minor Grammar Fix: Missing 'to' in sentence

### PR DESCRIPTION
**Pull request by vanyaeccles**
'To be', or not 'to be', that is the question!

Line 773 in docs/site/en/guide/intro_to_modules.ipynb

### CODE REVIEW

**Review by MarkDaoust — DISMISSED** [review]
Thanks.

**Comment by MarkDaoust** [comment]
Please sign the CLA so we can merge this.

**Comment by vanyaeccles** [comment]
@googlebot I signed it!

**Comment by vanyaeccles** [comment]
> Please sign the CLA so we can merge this.

Sorry Mark, I didn't flag that it was signed! Cheers

**Pull request merged**
