### PR TITLE
Update word2vec.ipynb

### PR DESCRIPTION
**Pull request by Yashashree304**
Fixes https://github.com/tensorflow/tensorflow/issues/50104

### CODE REVIEW

**Review by MarkDaoust — CHANGES_REQUESTED** [review]
Can you keep the original URL:

https://tensorflow.org/tutorials/text/images/word2vec_negative_sampling.png

And replace the old image at  images/word2vec_negative_sampling.png

Also please be sure you're using an actual PNG file, not a JPEG. JPEG is not a good format for diagrams.

**Comment by Yashashree304** [comment]
Made the necessary changes as told by you. However, the old file on the link is visible in the notebook, not the new file, I guess this is because my image is not hosted on the TensorFlow website.

**Comment by MarkDaoust** [comment]
Thanks. 

It doesn't show up yet, but after submission this will eventually get synced to tensorflow.org, and then the changes will be visible in the doc.
 
I could have been more clear about that.

**Comment by Yashashree304** [comment]
@MarkDaoust I have already done the changes as told by you. Do I need to make any more changes as I can see some changes are requested in the PR.

**Review by MarkDaoust — DISMISSED** [review]

**Comment by MarkDaoust** [comment]
I think Everything's okay here. Let me see if I can merge it.

**Comment by 8bitmp3** [comment]
Thanks @Yashashree304 @MarkDaoust On it (import/copybara)

**Comment by 8bitmp3** [comment]
@Yashashree304 There may be some issues with the grammar/syntax here:

image

Since the input `sentence` is `"The wide road shimmered in the hot sun"`, perhaps the following may be more straightforward:

```
Note: Words `temperature` and `code` are not part of the input sentence/vocabulary.
```

(Notice the back ticks.)

Since the remaining indices that you referred to in the last sentence do belong to the words from the input sentence, "similarly..." may not necessary/appropriate in this context.

LMKWYT

**Review by 8bitmp3 — APPROVED** [review]

**Comment by MarkDaoust** [comment]
That is an improvement, thanks @8bitmp3.

**Pull request merged**
