### PR TITLE
fix a typo in https://www.tensorflow.org/guide/upgrade

### PR DESCRIPTION
**Pull request by rushabh-v**
resolves https://github.com/tensorflow/tensorflow/issues/37800

### CODE REVIEW

**Comment by rushabh-v** [comment]
here is that notebook in my fork, https://github.com/rushabh-v/docs/blob/master/site/en/guide/upgrade.ipynb

**Comment by lamberta** [comment]
Thanks. To make the diffs easier to read, can you please run the notebook through [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) ?

**Comment by rushabh-v** [comment]
sure!
I was actually wondering if there was something like that!

**Comment by lamberta** [comment]
It's new and still testing it out. One day we can hopefully add it to the CI

**Comment by rushabh-v** [comment]
Done

**Comment by rushabh-v** [comment]
>It's new and still testing it out. One day we can hopefully add it to the CI

Oh, that's great!

**Pull request merged**
