### PR TITLE
Create Tuple Api 01 For GCI

### PR DESCRIPTION
**Pull request by CREVIOS**

### CODE REVIEW

**Comment by CREVIOS** [comment]
@googlebot I signed it!

**Comment by lamberta** [comment]
Not sure what this is

**Comment by CREVIOS** [comment]
But For google code in 2020 of Tensorflow task

**Comment by rish-16** [comment]
Hello @lamberta, I'm a mentor for TensorFlow. The other mentors and I are currently going through the code submission from @CREVIOS. He recently submitted the task for review.

**Comment by lamberta** [comment]
Are you creating a doc? Please read the TF docs contributor guide: https://www.tensorflow.org/community/contribute/docs

Also, use TF2 (no Sessions). 

You may want to start in the community section of the tensorflow/examples repo: https://github.com/tensorflow/examples/tree/master/community
Or communicate with us on the docs@tensorflow.org list before submitting

**Comment by rish-16** [comment]
Yup, I've just given the student more time to work on their submission. The task requires students to find methods without any usage examples and write one for them. Instead, this PR tries to add a new feature. 
I think we can close this one.

Thank you!

**Comment by MarkDaoust** [comment]
Cool, so usage examples of specific functions.

These should be written directly into the docstrings of the object you want to demonstrate, and written in doctest format.

See this doc for instructions: https://www.tensorflow.org/community/contribute/docs_ref

**Pull request closed without merging**
