### PR TITLE
fixed pickle error in the data loading code

### PR DESCRIPTION
**Pull request by VishwaPrabhakar**
the error due to pickling of object solved now in the basic text classification example by keras.

### CODE REVIEW

**Comment by VishwaPrabhakar** [comment]
I signed it! the CLA.

**Comment by lamberta** [comment]
Your diff was hard to read. If you save from Colab it's easier for us to see your change.

Also, we're about the switch the site over to TF2-first so the focus is now on docs in the `r2/` directory.

**Comment by yashk2810** [comment]
Isn't this fixed in tf-nightly?

There are instructions at the top of the notebook.

```
# keras.datasets.imdb is broken in 1.13 and 1.14, by np 1.16.3
!pip install tf_nightly
```

**Comment by MarkDaoust** [comment]
Thanks @VishwaPrabhakar, but it looks like the instructions  on the notebook are pretty clear.

We don't try to support old versions on master.

Thanks.

**Pull request closed without merging**
