### PR TITLE
KO translation - tutorials/keras/index, basic_text_classification, basic_regression

### PR DESCRIPTION
**Pull request by rickiepark**
Its rendering and result is ok with colab.
Thanks!

### CODE REVIEW

**Comment by rickiepark** [comment]
Thank you! I just like to learn more! :)

**Comment by rickiepark** [comment]
No problem. :)

**Comment by rickiepark** [comment]
Hi, @lamberta 
I finish to update basic_regression. 
Thanks.

**Comment by lamberta** [comment]
Great work, thank you!

**Comment by dynamicwebpaige** [comment]
This is awesome work, Rickie! Thanks so much for translating and for sharing. :1st_place_medal:

**Comment by rickiepark** [comment]
@lamberta Thank you!
@dynamicwebpaige Sure, My pleasure! :)

**Pull request merged**
