### PR TITLE
Simplify operations in word2vec tutorial

### PR DESCRIPTION
**Pull request by metric-space**
Replace operations in word2vec tutorial with simpler operations. Remove the unnecessary usage of `tf.squeeze` in many places

### CODE REVIEW

**Comment by metric-space** [comment]
Finished signing the cla just now, not sure how to restart the process

**Comment by metric-space** [comment]
comment to try rerunning cla check again

**Comment by 8bitmp3** [comment]
PTAL @MarkDaoust @markmcd

**Comment by markmcd** [comment]
LGTM

**Review by 8bitmp3 — APPROVED** [review]
Thanks @metric-space @markmcd

**Pull request merged**
