### PR TITLE
zh-CN：/tutorials/eager/custom_training_walkthrough.ipynb

### PR DESCRIPTION
**Pull request by KGBMAX**

### CODE REVIEW

**Comment by KGBMAX** [comment]
> I signed it!

**Comment by KGBMAX** [comment]
> I signed it!

**Comment by KGBMAX** [comment]
> I signed it!

**Comment by KGBMAX** [comment]
> I signed it!

**Comment by KGBMAX** [comment]
> I signed it!

**Comment by Mr-Linus** [comment]
@KGBMAX Maybe the e-mail of your github account is different with the email of the CLAs you signed. You may push the commit with the CLAs email and you should setting your git or github. 
See more: https://help.github.com/articles/setting-your-commit-email-address

**Comment by KGBMAX** [comment]
> Thanks! But it still doesn't work.

**Comment by Mr-Linus** [comment]
cc @lamberta

**Comment by lamberta** [comment]
@KGBMAX Thanks for the translation. I've manually confirmed your CLA.
The bot is not seeing you because your commit is using a different email address than what you signed the CLA with. You may need to update your `.gitconfig`

**Pull request merged**
