### PR TITLE
Tutorial: transfer learning using pretrained convnets

### PR DESCRIPTION
**Pull request by margaretmz**
A tutorial on transfer learning using a pretrained inception v3 model to classify cats / dogs images - demonstrates the scenarios of feature extraction and fine-tuning.

### CODE REVIEW

**Comment by lamberta** [comment]
Thanks, Margaret.

This notebook is similiar to [this one](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/_image_classification.ipynb), we should consolidate these.
@random-forests We should figure out a way to coordinate these so we don't duplicate work.

**Comment by margaretmz** [comment]
> Thanks, Margaret.
> 
> This notebook is similiar to [this one](https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/_image_classification.ipynb), we should consolidate these.
> @random-forests We should figure out a way to coordinate these so we don't duplicate work.

Thank you @lamberta for your comments. The tutorial you pointed out is "part 1" which covers image classification overfitting and data argumentation. My tutorial is "part 2" which covers transfer learning using a pretrained convnet. Both use the same dataset but it's not duplicate work.

**Comment by lamberta** [comment]
Preview: https://colab.research.google.com/github/margaretmz/docs/blob/margaret/transfer-learning/site/en/tutorials/images/transfer_learning.ipynb

**Comment by lamberta** [comment]
Thanks!
Verified CLA: signcla/margaretmz

**Comment by yashk2810** [comment]
Pulling this in to make changes.

**Comment by yashk2810** [comment]
@lamberta can you approve this?

**Pull request merged**
