### PR TITLE
Fix: save_to_tsv in word embedding tutorial

### PR DESCRIPTION
**Pull request by dreamnew**
#### Original code:
out_m.write(word + "\n")
out_v.write('\t'.join([str(x) for x in embeddings]) + "\n")
#### New Code:
out_m.write(word + "\n".encode('utf-8'))
out_v.write('\t'.join([str(x) for x in embeddings]).encode('utf-8') + "\n".encode('utf-8'))

### CODE REVIEW

**Comment by dreamnew** [comment]
I signed. Please review.

**Comment by lamberta** [comment]
@amit1rrr Hi Amit, can you look into the link that the ReviewNB bot is adding?
Getting the same permission error as seen before:
`Cannot access pull request. Please check permissions & verify url above.`

**Comment by lamberta** [comment]
@amit1rrr Thank you for the quick fix!

**Comment by lamberta** [comment]
Thanks, @dreamnew!
I think your indentation settings were throwing off the diffs, I went ahead and re-saved from Colab.

Confirmed this runs in Python3 and Python2 in Colab:
https://colab.research.google.com/github/dreamnew/docs/blob/master/site/en/r2/tutorials/sequences/word_embeddings.ipynb
@yashk2810 @MarkDaoust

**Comment by dreamnew** [comment]
Thanks @lamberta !

**Pull request closed without merging**
