### PR TITLE
Update function.ipynb

### PR DESCRIPTION
**Pull request by NinoRisteski**
two typo fixes in function.ipynb

### CODE REVIEW

**Review by MarkDaoust — APPROVED** [review]

**Comment by MarkDaoust** [comment]
Hey @NinoRisteski, thanks for the PR.

The change looks good, and I can see that you've signed the CLA, but the CLA bot won't let me merge because the email on the commit (95188570+NinoRisteski​@users.noreply.github.com) doesn't match the email you signed with. Can you resubmit without the "keep my email address private" option?

**Comment by NinoRisteski** [comment]
Hi @MarkDaoust, I just resubmitted with the same mail as my github profile. Hope its good now?

**Comment by MarkDaoust** [comment]
>  resubmitted

Where? I don't see any change or new PR.

**Comment by NinoRisteski** [comment]
I resubmitted the CLA with the same email as my GitHub profile. Should I make another commit, or new PR?

**Comment by MarkDaoust** [comment]
Cool, I can see that you've signed the CLA with two email addresses, the problem right now is that the commit itself is tagged with a different autogenerated address, not the one you signed the CLA with. So CLA bot doesn't recognize it as you. 

In the `checks` section check under the `details` link.

So I think you need to make a new PR, or fix it and force-push this branch.

**Comment by MarkDaoust** [comment]
Fixed in #2265

**Pull request closed without merging**
