### PR TITLE
Just fixed a small typo ("Shakespear") 😅

### PR DESCRIPTION
**Pull request by Vaseekaran-V**
Hi. I didn't push this change just to be a contributor but noticed this small typo, so thought to change it. I don't even know if it's a typo or an intended one. Thanks a lot for TensorFlow, TF had helped me a lot in my career and my academics ❤️

### CODE REVIEW

**Comment by Vaseekaran-V** [comment]
@googlebot I signed it!

**Comment by Vaseekaran-V** [comment]
Hi, really sorry. Just went through the notebook again, and saw it is an **intended** one. Really sorry for the inconvenience I have caused.

**Comment by lamberta** [comment]
No worries, thanks for investigating. There's lots of improvements and fixes that can still be made in the docs :)

**Comment by 8bitmp3** [comment]
> Thanks a lot for TensorFlow, TF had helped me a lot in my career and my academics ❤️

And thank you. Looking forward to your future contributions to the TensorFlow ecosystem.

**Pull request closed without merging**
