### PR TITLE
matplotlib.mlab issue solved

### PR DESCRIPTION
**Pull request by ayushmankumar7**
Issue : https://github.com/tensorflow/tensorflow/issues/37379

### CODE REVIEW

**Comment by lamberta** [comment]
Thanks. It's difficult to see the diff—can you please run it through [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) ?

**Comment by MarkDaoust** [comment]
> Thanks. It's difficult to see the diff—can you please run it through [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) ?

This should do it:

```
python tools/nbfmt.py site/en/tutorials/estimator/boosted_trees_model_understanding.ipynb
git add site/en/tutorials/estimator/boosted_trees_model_understanding.ipynb
git commit -m "reformat"
git push origin mlab
```

**Comment by ayushmankumar7** [comment]
@MarkDaoust It's done. Thanks for the help.

**Comment by MarkDaoust** [comment]
Okay, that worked as expected.... now that I can see the diff it's clear that the output is deleted.

This is one notebook where we need the output included. 

The easiest way to do that might just be: 

1. Open in colab, using the link from docs bot, above.
2. runtime -> run all
3. file -> save a copy in github

I think if you do it with jupyrter... npofmy will clear the outputs again , right @lamberta?

**Comment by lamberta** [comment]
Yeah, sorry about that. I think it may give you a warning, but for this notebook you need to run it like: `nbfmt.py --preserve_outputs notebook.ipynb`

**Comment by ayushmankumar7** [comment]
@MarkDaoust  Saving directly from Colab, deleted the outputs. I downloaded the .ipynb file and then did --preserve outputs.  Please Check if it's alright.

**Comment by MarkDaoust** [comment]
Thanks @ayushmankumar7, 

I'll resolve any outstanding issues and get this merged.

**Comment by ayushmankumar7** [comment]
Sure. Thanks

**Comment by ayushmankumar7** [comment]
Thanks for the approval

**Pull request merged**
