### PR TITLE
tf.reshape is added to fix the input dim to solve, ValueError: Input 0 of layer

### PR DESCRIPTION
**Pull request by MahdiRahbar**
Hello, 

As indicated in the "Denoise" class, the encoder's input dimension must be (28,28,1). However "x_train_noisy" and "x_test_noisy" have the shape of (n_images, 28, 28). Therefore the input image will have the shape of (28,28), which is not the one expected, and it runs to an error.  
The error is as follows: 

> ValueError: Input 0 of layer sequential_8 is incompatible with the layer: : expected min_ndim=4, found ndim=3. Full shape received: [None, 28, 28]

tf_error

I run Tensorflow 2.3.1, by the way.

### CODE REVIEW

**Comment by lamberta** [comment]
Looks like the CI is failing. Please format notebooks with `nbfmt`. Thank you

```
$ python3 -m pip install -U --user git+https://github.com/tensorflow/docs

$ python3 -m tensorflow_docs.tools.nbfmt notebook.ipynb
```

**Comment by MahdiRahbar** [comment]
> Looks like the CI is failing. Please format notebooks with `nbfmt`. Thank you
> 
> ```
> $ python3 -m pip install -U --user git+https://github.com/tensorflow/docs
> 
> $ python3 -m tensorflow_docs.tools.nbfmt notebook.ipynb
> ```

**Comment by MahdiRahbar** [comment]
@lamberta 
I formatted the notebook as you requested.

**Comment by lamberta** [comment]
cc @MarkDaoust @yashk2810

**Comment by 8bitmp3** [comment]
> the encoder's input dimension must be (28,28,1). However "x_train_noisy" and "x_test_noisy" have the shape of (n_images, 28, 28). Therefore the input image will have the shape of (28,28), which is not the one expected, and it runs to an error.

Hi, sorry about the wait. I've tested the notebook in TensorFlow 2.3.1 and 2.5. After adding random noise:

```
...
x_train_noisy = tf.clip_by_value(x_train_noisy, clip_value_min=0., clip_value_max=1.)
x_test_noisy = tf.clip_by_value(x_test_noisy, clip_value_min=0., clip_value_max=1.)
```

the shape of the noisy train and test sets: 

```
print(x_train_noisy.shape)
print(x_test_noisy.shape)
```
is:

```
(60000, 28, 28, 1)
(10000, 28, 28, 1)
```

Let us know if you still encounter any issues and we can reopen this PR.

**Pull request closed without merging**
