### PR TITLE
Fix site/en/tutorials/text/text_generation.ipynb

### PR DESCRIPTION
**Pull request by masa-ita**
Change "word"s to "character"s because the model is character-based.

### CODE REVIEW

**Comment by lamberta** [comment]
Thank you, @masa-ita (and sorry for the repetitive comments in your PRs :)

Community translations are now located in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo (see [this message](https://groups.google.com/a/tensorflow.org/g/docs/c/GJPq7S_fw4c/m/lA1qfBX2EQAJ) for context).

I'll move over/duplicate existing pull requests as I find time. In the meantime, please feel free to create a new pull request in that repo 😀 Then you can close this PR and add a link to the new one.

**Comment by masa-ita** [comment]
@lamberta 
Sorry.  This PR is not for a translation, but to fix terms in the original/english notebook.

**Comment by lamberta** [comment]
Sorry for overlooking, @masa-ita (too many PRs 😳)

**Comment by lamberta** [comment]
Diff is difficult to read because of the indentation change. Can you download from Colab, please? (The hope is to one day add an auto-formatter as part of the pre-merge process---but it doesn't exist, yet)

**Pull request merged**
