### PR TITLE
TensorFlow.js guides in Portuguese

### PR DESCRIPTION
**Pull request by gabrielrufino**
This is a translation of the TensorFlow.js guides for Portuguese. I wrote and reviewed to avoid and minimize errors!

If you find any errors, i ask for a fast feedback so I can make corrections.

Thank you! :D

### CODE REVIEW

**Comment by gabrielrufino** [comment]
@googlebot I signed it!

**Comment by lamberta** [comment]
Very nice. Thanks!
In the future, probably best to limit a single pull requests to one or two files---this makes it easier to find reviewers. But you can submit multiple PRs :)

**Comment by gabrielrufino** [comment]
My apologies. In my next PRs, I'll follow this rule.

Thank you!

**Comment by lamberta** [comment]
Thank you.

Community translations are now located in the [tensorflow/docs-l10n](https://github.com/tensorflow/docs-l10n) repo (see [this message](https://groups.google.com/a/tensorflow.org/g/docs/c/GJPq7S_fw4c/m/lA1qfBX2EQAJ) for context).

I'll move over/duplicate existing pull requests as I find time. In the meantime, please feel free to create a new pull request in that repo 😀 Then you can close this PR and add a link to the new one.

**Comment by gabrielrufino** [comment]
https://github.com/tensorflow/docs-l10n/pull/41

**Pull request closed without merging**
